// Copyright (c) Forged WoW LLC <https://github.com/ForgedWoW/ForgedCore>
// Licensed under GPL-3.0 license. See <https://github.com/ForgedWoW/ForgedCore/blob/master/LICENSE> for full information.

namespace Framework.Constants;

public enum QuestInfos
{
    Group = 1,
    Class = 21,
    Pvp = 41,
    Raid = 62,
    Dungeon = 81,
    WorldEvent = 82,
    Legendary = 83,
    Escort = 84,
    Heroic = 85,
    Raid10 = 88,
    Raid25 = 89,
    Scenario = 98,
    Account = 102,
    SideQuest = 104,
    Artifact = 107,
    WorldQuest = 109,
    EpicWorldQuest = 110,
    EliteWorldQuest = 111,
    EpicEliteWorldQuest = 112,
    PvpWorldQuest = 113,
    FirstAidWorldQuest = 114,
    BattlePetWorldQuest = 115,
    BlacksmithingWorldQuest = 116,
    LeatherworkingWorldQuest = 117,
    AlchemyWorldQuest = 118,
    HerbalismWorldQuest = 119,
    MiningWorldQuest = 120,
    TailoringWorldQuest = 121,
    EngineeringWorldQuest = 122,
    EnchantingWorldQuest = 123,
    SkinningWorldQuest = 124,
    JewelcraftingWorldQuest = 125,
    InscriptionWorldQuest = 126,
    EmissaryQuest = 128,
    ArcheologyWorldQuest = 129,
    FishingWorldQuest = 130,
    CookingWorldQuest = 131,
    RareWorldQuest = 135,
    RareEliteWorldQuest = 136,
    DungeonWorldQuest = 137,
    LegionInvasionWorldQuest = 139,
    RatedReward = 140,
    RaidWorldQuest = 141,
    LegionInvasionEliteWorldQuest = 142,
    LegionfallContribution = 143,
    LegionfallWorldQuest = 144,
    LegionfallDungeonWorldQuest = 145,
    LegionInvasionWorldQuestWrapper = 146,
    WarfrontBarrens = 147,
    Pickpocketing = 148,
    MagniWorldQuestAzerite = 151,
    TortollanWorldQuest = 152,
    WarfrontContribution = 153,
    IslandQuest = 254,
    WarMode = 255,
    PvpConquest = 256,
    FactionAssaultWorldQuest = 259,
    FactionAssaultEliteWorldQuest = 260,
    IslandWeeklyQuest = 261,
    PublicQuest = 263,
    ThreatObjective = 264,
    HiddenQuest = 265,
    CombatAllyQuest = 266,
    Professions = 267,
    ThreatWrapper = 268,
    ThreatEmissaryQuest = 270,
    CallingQuest = 271,
    VenthyrPartyQuest = 272,
    MawSoulSpawnTracker = 273
}