// Copyright (c) Forged WoW LLC <https://github.com/ForgedWoW/ForgedCore>
// Licensed under GPL-3.0 license. See <https://github.com/ForgedWoW/ForgedCore/blob/master/LICENSE> for full information.

namespace Framework.Constants;

public enum InventoryResult
{
    Ok = 0,
    CantEquipLevelI = 1,               // You Must Reach Level %D To Use That Item.
    CantEquipSkill = 2,                // You Aren'T Skilled Enough To Use That Item.
    WrongSlot = 3,                     // That Item Does Not Go In That Slot.
    BagFull = 4,                       // That Bag Is Full.
    BagInBag = 5,                      // Can'T Put Non-Empty Bags In Other Bags.
    TradeEquippedBag = 6,              // You Can'T Trade Equipped Bags.
    AmmoOnly = 7,                      // Only Ammo Can Go There.
    ProficiencyNeeded = 8,             // You Do Not Have The Required Proficiency For That Item.
    NoSlotAvailable = 9,               // No Equipment Slot Is Available For That Item.
    CantEquipEver = 10,                // You Can Never Use That Item.
    CantEquipEver2 = 11,               // You Can Never Use That Item.
    NoSlotAvailable2 = 12,             // No Equipment Slot Is Available For That Item.
    Equipped2handed = 13,              // Cannot Equip That With A Two-Handed Weapon.
    TwoHandSkillNotFound = 14,         // You Cannot Dual-Wield
    WrongBagType = 15,                 // That Item Doesn'T Go In That Container.
    WrongBagType2 = 16,                // That Item Doesn'T Go In That Container.
    ItemMaxCount = 17,                 // You Can'T Carry Any More Of Those Items.
    NoSlotAvailable3 = 18,             // No Equipment Slot Is Available For That Item.
    CantStack = 19,                    // This Item Cannot Stack.
    NotEquippable = 20,                // This Item Cannot Be Equipped.
    CantSwap = 21,                     // These Items Can'T Be Swapped.
    SlotEmpty = 22,                    // That Slot Is Empty.
    ItemNotFound = 23,                 // The Item Was Not Found.
    DropBoundItem = 24,                // You Can'T Drop A Soulbound Item.
    OutOfRange = 25,                   // Out Of Range.
    TooFewToSplit = 26,                // Tried To Split More Than Number In Stack.
    SplitFailed = 27,                  // Couldn'T Split Those Items.
    SpellFailedReagentsGeneric = 28,   // Missing Reagent
    CantTradeGold = 29,                // Gold May Only Be Offered By One Trader.
    NotEnoughMoney = 30,               // You Don'T Have Enough Money.
    NotABag = 31,                      // Not A Bag.
    DestroyNonemptyBag = 32,           // You Can Only Do That With Empty Bags.
    NotOwner = 33,                     // You Don'T Own That Item.
    OnlyOneQuiver = 34,                // You Can Only Equip One Quiver.
    NoBankSlot = 35,                   // You Must Purchase That Bag Slot First
    NoBankHere = 36,                   // You Are Too Far Away From A Bank.
    ItemLocked = 37,                   // Item Is Locked.
    GenericStunned = 38,               // You Are Stunned
    PlayerDead = 39,                   // You Can'T Do That When You'Re Dead.
    ClientLockedOut = 40,              // You Can'T Do That Right Now.
    InternalBagError = 41,             // Internal Bag Error
    OnlyOneBolt = 42,                  // You Can Only Equip One Quiver.
    OnlyOneAmmo = 43,                  // You Can Only Equip One Ammo Pouch.
    CantWrapStackable = 44,            // Stackable Items Can'T Be Wrapped.
    CantWrapEquipped = 45,             // Equipped Items Can'T Be Wrapped.
    CantWrapWrapped = 46,              // Wrapped Items Can'T Be Wrapped.
    CantWrapBound = 47,                // Bound Items Can'T Be Wrapped.
    CantWrapUnique = 48,               // Unique Items Can'T Be Wrapped.
    CantWrapBags = 49,                 // Bags Can'T Be Wrapped.
    LootGone = 50,                     // Already Looted
    InvFull = 51,                      // Inventory Is Full.
    BankFull = 52,                     // Your Bank Is Full
    VendorSoldOut = 53,                // That Item Is Currently Sold Out.
    BagFull2 = 54,                     // That Bag Is Full.
    ItemNotFound2 = 55,                // The Item Was Not Found.
    CantStack2 = 56,                   // This Item Cannot Stack.
    BagFull3 = 57,                     // That Bag Is Full.
    VendorSoldOut2 = 58,               // That Item Is Currently Sold Out.
    ObjectIsBusy = 59,                 // That Object Is Busy.
    CantBeDisenchanted = 60,           // Item Cannot Be Disenchanted
    NotInCombat = 61,                  // You Can'T Do That While In Combat
    NotWhileDisarmed = 62,             // You Can'T Do That While Disarmed
    BagFull4 = 63,                     // That Bag Is Full.
    CantEquipRank = 64,                // You Don'T Have The Required Rank For That Item
    CantEquipReputation = 65,          // You Don'T Have The Required Reputation For That Item
    TooManySpecialBags = 66,           // You Cannot Equip Another Bag Of That Type
    LootCantLootThatNow = 67,          // You Can'T Loot That Item Now.
    ItemUniqueEquippable = 68,         // You Cannot Equip More Than One Of Those.
    VendorMissingTurnins = 69,         // You Do Not Have The Required Items For That Purchase
    NotEnoughHonorPoints = 70,         // You Don'T Have Enough Honor Points
    NotEnoughArenaPoints = 71,         // You Don'T Have Enough Arena Points
    ItemMaxCountSocketed = 72,         // You Have The Maximum Number Of Those Gems In Your Inventory Or Socketed Into Items.
    MailBoundItem = 73,                // You Can'T Mail Soulbound Items.
    InternalBagError2 = 74,            // Internal Bag Error
    BagFull5 = 75,                     // That Bag Is Full.
    ItemMaxCountEquippedSocketed = 76, // You Have The Maximum Number Of Those Gems Socketed Into Equipped Items.
    ItemUniqueEquippableSocketed = 77, // You Cannot Socket More Than One Of Those Gems Into A Single Item.
    TooMuchGold = 78,                  // At Gold Limit
    NotDuringArenaMatch = 79,          // You Can'T Do That While In An Arena Match
    TradeBoundItem = 80,               // You Can'T Trade A Soulbound Item.
    CantEquipRating = 81,              // You Don'T Have The Personal, Team, Or Battleground Rating Required To Buy That Item
    EventAutoequipBindConfirm = 82,
    NotSameAccount = 83, // Account-Bound Items Can Only Be Given To Your Own Characters.
    EquipNone3 = 84,
    ItemMaxLimitCategoryCountExceededIs = 85,    // You Can Only Carry %D %S
    ItemMaxLimitCategorySocketedExceededIs = 86, // You Can Only Equip %D |4item:Items In The %S Category
    ScalingStatItemLevelExceeded = 87,           // Your Level Is Too High To Use That Item
    PurchaseLevelTooLow = 88,                    // You Must Reach Level %D To Purchase That Item.
    CantEquipNeedTalent = 89,                    // You Do Not Have The Required Talent To Equip That.
    ItemMaxLimitCategoryEquippedExceededIs = 90, // You Can Only Equip %D |4item:Items In The %S Category
    ShapeshiftFormCannotEquip = 91,              // Cannot Equip Item In This Form
    ItemInventoryFullSatchel = 92,               // Your Inventory Is Full. Your Satchel Has Been Delivered To Your Mailbox.
    ScalingStatItemLevelTooLow = 93,             // Your Level Is Too Low To Use That Item
    CantBuyQuantity = 94,                        // You Can'T Buy The Specified Quantity Of That Item.
    ItemIsBattlePayLocked = 95,                  // Your Purchased Item Is Still Waiting To Be Unlocked
    ReagentBankFull = 96,                        // Your Reagent Bank Is Full
    ReagentBankLocked = 97,
    WrongBagType3 = 98,           // That Item Doesn'T Go In That Container.
    CantUseItem = 99,             // You Can'T Use That Item.
    CantBeObliterated = 100,      // You Can'T Obliterate That Item
    GuildBankConjuredItem = 101,  // You Cannot Store Conjured Items In The Guild Bank
    BagFull6 = 102,               // That bag is full.
    BagFull7 = 103,               // That bag is full.
    CantBeScrapped = 104,         // You can't scrap that item
    BagFull8 = 105,               // That bag is full.
    NotInPetBattle = 106,         // You cannot do that while in a pet battle
    BagFull9 = 107,               // That bag is full.
    CantDoThatRightNow = 108,     // You can't do that right now.
    CantDoThatRightNow2 = 109,    // You can't do that right now.
    NotInNPE = 110,               // Not available during the tutorial
    ItemCooldown = 111,           // Item is not ready yet.
    NotInRatedBattleground = 112, // You can't do that in a rated battleground.
    EquipableSpellsSlotsFull = 113,
    CantBeRecrafted = 114,     // You can't recraft that itemv
    ReagentBagWrongSlot = 115, // Reagent Bags can only be placed in the reagent bag slot.
    SlotOnlyReagentBag = 116,  // Only Reagent Bags can be placed in the reagent bag slot.
    ReagentBagItemType = 117,  // Only Reagents can be placed in Reagent Bags.
}