// Copyright (c) Forged WoW LLC <https://github.com/ForgedWoW/ForgedCore>
// Licensed under GPL-3.0 license. See <https://github.com/ForgedWoW/ForgedCore/blob/master/LICENSE> for full information.

namespace Framework.Constants;

public enum ItemModifier
{
    TransmogAppearanceAllSpecs = 0,
    TransmogAppearanceSpec1 = 1,
    UpgradeId = 2,
    BattlePetSpeciesId = 3,
    BattlePetBreedData = 4, // (Breedid) | (Breedquality << 24)
    BattlePetLevel = 5,
    BattlePetDisplayId = 6,
    EnchantIllusionAllSpecs = 7,
    ArtifactAppearanceId = 8,
    TimewalkerLevel = 9,
    EnchantIllusionSpec1 = 10,
    TransmogAppearanceSpec2 = 11,
    EnchantIllusionSpec2 = 12,
    TransmogAppearanceSpec3 = 13,
    EnchantIllusionSpec3 = 14,
    TransmogAppearanceSpec4 = 15,
    EnchantIllusionSpec4 = 16,
    ChallengeMapChallengeModeId = 17,
    ChallengeKeystoneLevel = 18,
    ChallengeKeystoneAffixId1 = 19,
    ChallengeKeystoneAffixId2 = 20,
    ChallengeKeystoneAffixId3 = 21,
    ChallengeKeystoneAffixId4 = 22,
    ArtifactKnowledgeLevel = 23,
    ArtifactTier = 24,
    TransmogAppearanceSpec5 = 25,
    PvpRating = 26,
    EnchantIllusionSpec5 = 27,
    ContentTuningId = 28,
    ChangeModifiedCraftingStat1 = 29,
    ChangeModifiedCraftingStat2 = 30,
    TransmogSecondaryAppearanceAllSpecs = 31,
    TransmogSecondaryAppearanceSpec1 = 32,
    TransmogSecondaryAppearanceSpec2 = 33,
    TransmogSecondaryAppearanceSpec3 = 34,
    TransmogSecondaryAppearanceSpec4 = 35,
    TransmogSecondaryAppearanceSpec5 = 36,
    SoulbindConduitRank = 37,
    CraftingQualityId = 38,
    CraftingSkillLineAbilityId = 39,
    CraftingDataId = 40,
    CraftingSkillReagents = 41,
    CraftingSkillWatermark = 42,
    CraftingReagentSlot0 = 43,
    CraftingReagentSlot1 = 44,
    CraftingReagentSlot2 = 45,
    CraftingReagentSlot3 = 46,
    CraftingReagentSlot4 = 47,
    CraftingReagentSlot5 = 48,
    CraftingReagentSlot6 = 49,
    CraftingReagentSlot7 = 50,
    CraftingReagentSlot8 = 51,
    CraftingReagentSlot9 = 52,
    CraftingReagentSlot10 = 53,
    CraftingReagentSlot11 = 54,
    CraftingReagentSlot12 = 55,
    CraftingReagentSlot13 = 56,
    CraftingReagentSlot14 = 57,

    Max
}