// Copyright (c) Forged WoW LLC <https://github.com/ForgedWoW/ForgedCore>
// Licensed under GPL-3.0 license. See <https://github.com/ForgedWoW/ForgedCore/blob/master/LICENSE> for full information.

namespace Framework.Constants;

public enum ItemModType
{
	Mana = 0,
	Health = 1,
	Agility = 3,
	Strength = 4,
	Intellect = 5,
	Spirit = 6,
	Stamina = 7,
	DefenseSkillRating = 12,
	DodgeRating = 13,
	ParryRating = 14,
	BlockRating = 15,
	HitMeleeRating = 16,
	HitRangedRating = 17,
	HitSpellRating = 18,
	CritMeleeRating = 19,
	CritRangedRating = 20,
	CritSpellRating = 21,
	Corruption = 22,
	CorruptionResistance = 23,
	ModifiedCraftingStat1 = 24,
	ModifiedCraftingStat2 = 25,
	CritTakenRangedRating = 26,
	CritTakenSpellRating = 27,
	HasteMeleeRating = 28,
	HasteRangedRating = 29,
	HasteSpellRating = 30,
	HitRating = 31,
	CritRating = 32,
	HitTakenRating = 33,
	CritTakenRating = 34,
	ResilienceRating = 35,
	HasteRating = 36,
	ExpertiseRating = 37,
	AttackPower = 38,
	RangedAttackPower = 39,
	Versatility = 40,
	SpellHealingDone = 41,
	SpellDamageDone = 42,
	ManaRegeneration = 43,
	ArmorPenetrationRating = 44,
	SpellPower = 45,
	HealthRegen = 46,
	SpellPenetration = 47,
	BlockValue = 48,
	MasteryRating = 49,
	ExtraArmor = 50,
	FireResistance = 51,
	FrostResistance = 52,
	HolyResistance = 53,
	ShadowResistance = 54,
	NatureResistance = 55,
	ArcaneResistance = 56,
	PvpPower = 57,
	Unused0 = 58,
	Unused1 = 59,
	Unused3 = 60,
	CrSpeed = 61,
	CrLifesteal = 62,
	CrAvoidance = 63,
	CrSturdiness = 64,
	CrUnused7 = 65,
	Unused27 = 66,
	CrUnused9 = 67,
	CrUnused10 = 68,
	CrUnused11 = 69,
	CrUnused12 = 70,
	AgiStrInt = 71,
	AgiStr = 72,
	AgiInt = 73,
	StrInt = 74
}