// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ClientTradingPost.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Blizzard.Telemetry.Wow.Client.TradingPost {

  /// <summary>Holder for reflection information generated from ClientTradingPost.proto</summary>
  public static partial class ClientTradingPostReflection {

    #region Descriptor
    /// <summary>File descriptor for ClientTradingPost.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ClientTradingPostReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChdDbGllbnRUcmFkaW5nUG9zdC5wcm90bxIpQmxpenphcmQuVGVsZW1ldHJ5",
            "Lldvdy5DbGllbnQuVHJhZGluZ1Bvc3QaGnRlbGVtZXRyeV9leHRlbnNpb25z",
            "LnByb3RvGiJUZWxlbWV0cnlTaGFyZWRDbGllbnRJbXBvcnRzLnByb3RvIpUC",
            "ChFUcmFkaW5nUG9zdENsb3NlZBI5CgZjbGllbnQYASABKAsyKS5CbGl6emFy",
            "ZC5UZWxlbWV0cnkuV293LkNsaWVudC5DbGllbnRJbmZvEjcKBXdvcmxkGAIg",
            "ASgLMiguQmxpenphcmQuVGVsZW1ldHJ5Lldvdy5DbGllbnQuV29ybGRJbmZv",
            "EhgKEG9wZW5lZF90aW1lc3RhbXAYAyABKAQSGAoQY2xvc2VkX3RpbWVzdGFt",
            "cBgEIAEoBBJPCg5pdGVtc19zZWxlY3RlZBgFIAMoCzI3LkJsaXp6YXJkLlRl",
            "bGVtZXRyeS5Xb3cuQ2xpZW50LlRyYWRpbmdQb3N0SXRlbVNlbGVjdGlvbjoH",
            "wswlA6AGAA=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Blizzard.Telemetry.TelemetryExtensionsReflection.Descriptor, global::Blizzard.Telemetry.Wow.Client.TelemetrySharedClientImportsReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Blizzard.Telemetry.Wow.Client.TradingPost.TradingPostClosed), global::Blizzard.Telemetry.Wow.Client.TradingPost.TradingPostClosed.Parser, new[]{ "Client", "World", "OpenedTimestamp", "ClosedTimestamp", "ItemsSelected" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class TradingPostClosed : pb::IMessage<TradingPostClosed>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TradingPostClosed> _parser = new pb::MessageParser<TradingPostClosed>(() => new TradingPostClosed());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TradingPostClosed> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Blizzard.Telemetry.Wow.Client.TradingPost.ClientTradingPostReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TradingPostClosed() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TradingPostClosed(TradingPostClosed other) : this() {
      _hasBits0 = other._hasBits0;
      client_ = other.client_ != null ? other.client_.Clone() : null;
      world_ = other.world_ != null ? other.world_.Clone() : null;
      openedTimestamp_ = other.openedTimestamp_;
      closedTimestamp_ = other.closedTimestamp_;
      itemsSelected_ = other.itemsSelected_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TradingPostClosed Clone() {
      return new TradingPostClosed(this);
    }

    /// <summary>Field number for the "client" field.</summary>
    public const int ClientFieldNumber = 1;
    private global::Blizzard.Telemetry.Wow.Client.ClientInfo client_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Blizzard.Telemetry.Wow.Client.ClientInfo Client {
      get { return client_; }
      set {
        client_ = value;
      }
    }

    /// <summary>Field number for the "world" field.</summary>
    public const int WorldFieldNumber = 2;
    private global::Blizzard.Telemetry.Wow.Client.WorldInfo world_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Blizzard.Telemetry.Wow.Client.WorldInfo World {
      get { return world_; }
      set {
        world_ = value;
      }
    }

    /// <summary>Field number for the "opened_timestamp" field.</summary>
    public const int OpenedTimestampFieldNumber = 3;
    private readonly static ulong OpenedTimestampDefaultValue = 0UL;

    private ulong openedTimestamp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong OpenedTimestamp {
      get { if ((_hasBits0 & 1) != 0) { return openedTimestamp_; } else { return OpenedTimestampDefaultValue; } }
      set {
        _hasBits0 |= 1;
        openedTimestamp_ = value;
      }
    }
    /// <summary>Gets whether the "opened_timestamp" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasOpenedTimestamp {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "opened_timestamp" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearOpenedTimestamp() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "closed_timestamp" field.</summary>
    public const int ClosedTimestampFieldNumber = 4;
    private readonly static ulong ClosedTimestampDefaultValue = 0UL;

    private ulong closedTimestamp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong ClosedTimestamp {
      get { if ((_hasBits0 & 2) != 0) { return closedTimestamp_; } else { return ClosedTimestampDefaultValue; } }
      set {
        _hasBits0 |= 2;
        closedTimestamp_ = value;
      }
    }
    /// <summary>Gets whether the "closed_timestamp" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasClosedTimestamp {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "closed_timestamp" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearClosedTimestamp() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "items_selected" field.</summary>
    public const int ItemsSelectedFieldNumber = 5;
    private static readonly pb::FieldCodec<global::Blizzard.Telemetry.Wow.Client.TradingPostItemSelection> _repeated_itemsSelected_codec
        = pb::FieldCodec.ForMessage(42, global::Blizzard.Telemetry.Wow.Client.TradingPostItemSelection.Parser);
    private readonly pbc::RepeatedField<global::Blizzard.Telemetry.Wow.Client.TradingPostItemSelection> itemsSelected_ = new pbc::RepeatedField<global::Blizzard.Telemetry.Wow.Client.TradingPostItemSelection>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Blizzard.Telemetry.Wow.Client.TradingPostItemSelection> ItemsSelected {
      get { return itemsSelected_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TradingPostClosed);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TradingPostClosed other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Client, other.Client)) return false;
      if (!object.Equals(World, other.World)) return false;
      if (OpenedTimestamp != other.OpenedTimestamp) return false;
      if (ClosedTimestamp != other.ClosedTimestamp) return false;
      if(!itemsSelected_.Equals(other.itemsSelected_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (client_ != null) hash ^= Client.GetHashCode();
      if (world_ != null) hash ^= World.GetHashCode();
      if (HasOpenedTimestamp) hash ^= OpenedTimestamp.GetHashCode();
      if (HasClosedTimestamp) hash ^= ClosedTimestamp.GetHashCode();
      hash ^= itemsSelected_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (client_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Client);
      }
      if (world_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(World);
      }
      if (HasOpenedTimestamp) {
        output.WriteRawTag(24);
        output.WriteUInt64(OpenedTimestamp);
      }
      if (HasClosedTimestamp) {
        output.WriteRawTag(32);
        output.WriteUInt64(ClosedTimestamp);
      }
      itemsSelected_.WriteTo(output, _repeated_itemsSelected_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (client_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Client);
      }
      if (world_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(World);
      }
      if (HasOpenedTimestamp) {
        output.WriteRawTag(24);
        output.WriteUInt64(OpenedTimestamp);
      }
      if (HasClosedTimestamp) {
        output.WriteRawTag(32);
        output.WriteUInt64(ClosedTimestamp);
      }
      itemsSelected_.WriteTo(ref output, _repeated_itemsSelected_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (client_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Client);
      }
      if (world_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(World);
      }
      if (HasOpenedTimestamp) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(OpenedTimestamp);
      }
      if (HasClosedTimestamp) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(ClosedTimestamp);
      }
      size += itemsSelected_.CalculateSize(_repeated_itemsSelected_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TradingPostClosed other) {
      if (other == null) {
        return;
      }
      if (other.client_ != null) {
        if (client_ == null) {
          Client = new global::Blizzard.Telemetry.Wow.Client.ClientInfo();
        }
        Client.MergeFrom(other.Client);
      }
      if (other.world_ != null) {
        if (world_ == null) {
          World = new global::Blizzard.Telemetry.Wow.Client.WorldInfo();
        }
        World.MergeFrom(other.World);
      }
      if (other.HasOpenedTimestamp) {
        OpenedTimestamp = other.OpenedTimestamp;
      }
      if (other.HasClosedTimestamp) {
        ClosedTimestamp = other.ClosedTimestamp;
      }
      itemsSelected_.Add(other.itemsSelected_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (client_ == null) {
              Client = new global::Blizzard.Telemetry.Wow.Client.ClientInfo();
            }
            input.ReadMessage(Client);
            break;
          }
          case 18: {
            if (world_ == null) {
              World = new global::Blizzard.Telemetry.Wow.Client.WorldInfo();
            }
            input.ReadMessage(World);
            break;
          }
          case 24: {
            OpenedTimestamp = input.ReadUInt64();
            break;
          }
          case 32: {
            ClosedTimestamp = input.ReadUInt64();
            break;
          }
          case 42: {
            itemsSelected_.AddEntriesFrom(input, _repeated_itemsSelected_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (client_ == null) {
              Client = new global::Blizzard.Telemetry.Wow.Client.ClientInfo();
            }
            input.ReadMessage(Client);
            break;
          }
          case 18: {
            if (world_ == null) {
              World = new global::Blizzard.Telemetry.Wow.Client.WorldInfo();
            }
            input.ReadMessage(World);
            break;
          }
          case 24: {
            OpenedTimestamp = input.ReadUInt64();
            break;
          }
          case 32: {
            ClosedTimestamp = input.ReadUInt64();
            break;
          }
          case 42: {
            itemsSelected_.AddEntriesFrom(ref input, _repeated_itemsSelected_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
