// Copyright (c) Forged WoW LLC <https://github.com/ForgedWoW/ForgedCore>
// Licensed under GPL-3.0 license. See <https://github.com/ForgedWoW/ForgedCore/blob/master/LICENSE> for full information.

namespace Framework.Constants;

public enum CriteriaType : byte
{
	KillCreature = 0,                                        // Kill NPC "{Creature}"
	WinBattleground = 1,                                     // Win battleground "{Map}"
	CompleteResearchProject = 2, /*NYI*/                     // Complete research project "{ResearchProject}"
	CompleteAnyResearchProject = 3, /*NYI*/                  // Complete any research project
	FindResearchObject = 4, /*NYI*/                          // Find research object "{GameObjects}"
	ReachLevel = 5,                                          // Reach level
	ExhaustAnyResearchSite = 6, /*NYI*/                      // Exhaust any research site
	SkillRaised = 7,                                         // Skill "{SkillLine}" raised
	EarnAchievement = 8,                                     // Earn achievement "{Achievement}"
	CompleteQuestsCount = 9,                                 // Count of complete quests (quest count)
	CompleteAnyDailyQuestPerDay = 10,                        // Complete any daily quest (per day)
	CompleteQuestsInZone = 11,                               // Complete quests in "{AreaTable}"
	CurrencyGained = 12,                                     // Currency "{CurrencyTypes}" gained
	DamageDealt = 13,                                        // Damage dealt
	CompleteDailyQuest = 14,                                 // Complete daily quest
	ParticipateInBattleground = 15,                          // Participate in battleground "{Map}"
	DieOnMap = 16,                                           // Die on map "{Map}"
	DieAnywhere = 17,                                        // Die anywhere
	DieInInstance = 18,                                      // Die in an instance which handles at most {#Max Players} players
	RunInstance = 19, /*NYI*/                                // Run an instance which handles at most {#Max Players} players
	KilledByCreature = 20,                                   // Get killed by "{Creature}"
	CompleteInternalCriteria = 21, /*NYI*/                   // Designer Value{`Uses Record ID}
	CompleteAnyChallengeMode = 22, /*NYI*/                   // Complete any challenge mode
	KilledByPlayer = 23,                                     // Die to a player
	MaxDistFallenWithoutDying = 24,                          // Maximum distance fallen without dying
	EarnChallengeModeMedal = 25, /*NYI*/                     // Earn a challenge mode medal of "{#Challenge Mode Medal (OBSOLETE)}" (OBSOLETE)
	DieFromEnviromentalDamage = 26,                          // Die to "{$Env Damage}" environmental damage
	CompleteQuest = 27,                                      // Complete quest "{QuestV2}"
	BeSpellTarget = 28,                                      // Have the spell "{Spell}" cast on you
	CastSpell = 29,                                          // Cast the spell "{Spell}"
	TrackedWorldStateUIModified = 30,                        // Tracked WorldStateUI value "{WorldStateUI}" is modified
	PVPKillInArea = 31,                                      // Kill someone in PVP in "{AreaTable}"
	WinArena = 32,                                           // Win arena "{Map}"
	ParticipateInArena = 33, /*NYI*/                         // Participate in arena "{Map}"
	LearnOrKnowSpell = 34,                                   // Learn or Know spell "{Spell}"
	EarnHonorableKill = 35,                                  // Earn an honorable kill
	AcquireItem = 36,                                        // Acquire item "{Item}"
	WinAnyRankedArena = 37,                                  // Win a ranked arena match (any arena)
	EarnTeamArenaRating = 38, /*NYI*/                        // Earn a team arena rating of {#Arena Rating}
	EarnPersonalArenaRating = 39,                            // Earn a personal arena rating of {#Arena Rating}
	AchieveSkillStep = 40,                                   // Achieve a skill step in "{SkillLine}"
	UseItem = 41,                                            // Use item "{Item}"
	LootItem = 42,                                           // Loot "{Item}" via corpse, pickpocket, fishing, disenchanting, etc.
	RevealWorldMapOverlay = 43,                              // Reveal world map overlay "{WorldMapOverlay}"
	EarnTitle = 44, /*NYI*/                                  // Deprecated PVP Titles
	BankSlotsPurchased = 45,                                 // Bank slots purchased
	ReputationGained = 46,                                   // Reputation gained with faction "{Faction}"
	TotalExaltedFactions = 47,                               // Total exalted factions
	GotHaircut = 48,                                         // Got a haircut
	EquipItemInSlot = 49,                                    // Equip item in slot "{$Equip Slot}"
	RollNeed = 50,                                           // Roll need and get {#Need Roll}
	RollGreed = 51,                                          // Roll greed and get {#Greed Roll}
	DeliverKillingBlowToClass = 52,                          // Deliver a killing blow to a {ChrClasses}
	DeliverKillingBlowToRace = 53,                           // Deliver a killing blow to a {ChrRaces}
	DoEmote = 54,                                            // Do a "{EmotesText}" emote
	HealingDone = 55,                                        // Healing done
	DeliveredKillingBlow = 56,                               // Delivered a killing blow
	EquipItem = 57,                                          // Equip item "{Item}"
	CompleteQuestsInSort = 58, /*NYI*/                       // Complete quests in "{QuestSort}"
	MoneyEarnedFromSales = 59,                               // Sell items to vendors
	MoneySpentOnRespecs = 60,                                // Money spent on respecs
	TotalRespecs = 61,                                       // Total respecs
	MoneyEarnedFromQuesting = 62,                            // Money earned from questing
	MoneySpentOnTaxis = 63,                                  // Money spent on taxis
	KilledAllUnitsInSpawnRegion = 64, /*NYI*/                // Killed all units in spawn region "{SpawnRegion}"
	MoneySpentAtBarberShop = 65,                             // Money spent at the barber shop
	MoneySpentOnPostage = 66,                                // Money spent on postage
	MoneyLootedFromCreatures = 67,                           // Money looted from creatures
	UseGameobject = 68,                                      // Use Game Object "{GameObjects}"
	GainAura = 69,                                           // Gain aura "{Spell}"
	KillPlayer = 70,                                         // Kill a player (no honor check)
	CompleteChallengeMode = 71, /*NYI*/                      // Complete a challenge mode on map "{Map}"
	CatchFishInFishingHole = 72,                             // Catch fish in the "{GameObjects}" fishing hole
	PlayerTriggerGameEvent = 73, /*NYI*/                     // Player will Trigger game event "{GameEvents}"
	Login = 74,                                              // Login (USE SPARINGLY!)
	LearnSpellFromSkillLine = 75,                            // Learn spell from the "{SkillLine}" skill line
	WinDuel = 76,                                            // Win a duel
	LoseDuel = 77,                                           // Lose a duel
	KillAnyCreature = 78,                                    // Kill any NPC
	CreatedItemsByCastingSpellWithLimit = 79, /*NYI*/        // Created items by casting a spell (limit 1 per create...)
	MoneyEarnedFromAuctions = 80,                            // Money earned from auctions
	BattlePetAchievementPointsEarned = 81, /*NYI*/           // Battle pet achievement points earned
	ItemsPostedAtAuction = 82,                               // Number of items posted at auction
	HighestAuctionBid = 83,                                  // Highest auction bid
	AuctionsWon = 84,                                        // Auctions won
	HighestAuctionSale = 85,                                 // Highest coin value of item sold
	MostMoneyOwned = 86,                                     // Most money owned
	TotalReveredFactions = 87,                               // Total revered factions
	TotalHonoredFactions = 88,                               // Total honored factions
	TotalFactionsEncountered = 89,                           // Total factions encountered
	LootAnyItem = 90,                                        // Loot any item
	ObtainAnyItem = 91,                                      // Obtain any item
	AnyoneTriggerGameEventScenario = 92, /*NYI*/             // Anyone will Trigger game event "{GameEvents}" (Scenario Only)
	RollAnyNeed = 93,                                        // Roll any number on need
	RollAnyGreed = 94,                                       // Roll any number on greed
	ReleasedSpirit = 95, /*NYI*/                             // Released Spirit
	AccountKnownPet = 96, /*NYI*/                            // Account knows pet "{Creature}" (Backtracked)
	DefeatDungeonEncounterWhileElegibleForLoot = 97, /*NYI*/ // Defeat Encounter "{DungeonEncounter}" While Eligible For Loot

	// UNUSED 18{}                                 = 98,  // Unused
	// UNUSED 19{}                                 = 99,  // Unused
	// UNUSED 20{}                                 = 100, // Unused
	HighestDamageDone = 101,         // Highest damage done in 1 single ability
	HighestDamageTaken = 102,        // Most damage taken in 1 single hit
	TotalDamageTaken = 103,          // Total damage taken
	HighestHealCast = 104,           // Largest heal cast
	TotalHealReceived = 105,         // Total healing received
	HighestHealReceived = 106,       // Largest heal received
	AbandonAnyQuest = 107,           // Abandon any quest
	BuyTaxi = 108,                   // Buy a taxi
	GetLootByType = 109,             // Get loot via "{$Loot Acquisition}"
	LandTargetedSpellOnTarget = 110, // Land targeted spell "{Spell}" on a target

	// UNUSED 21{}                                 = 111, // Unused
	LearnTradeskillSkillLine = 112,                          // Learn tradeskill skill line "{SkillLine}"
	HonorableKills = 113,                                    // Honorable kills (number in interface, won't update except for login)
	AcceptSummon = 114,                                      // Accept a summon
	EarnAchievementPoints = 115,                             // Earn achievement points
	RollDisenchant = 116, /*NYI*/                            // Roll disenchant and get {#Disenchant Roll}
	RollAnyDisenchant = 117, /*NYI*/                         // Roll any number on disenchant
	CompletedLFGDungeon = 118, /*NYI*/                       // Completed an LFG dungeon
	CompletedLFGDungeonWithStrangers = 119,                  // Completed an LFG dungeon with strangers
	KickInitiatorInLFGDungeon = 120, /*NYI*/                 // Kicked in an LFG dungeon (initiator)
	KickVoterInLFGDungeon = 121, /*NYI*/                     // Kicked in an LFG dungeon (voter)
	KickTargetInLFGDungeon = 122, /*NYI*/                    // Kicked in an LFG dungeon (target)
	AbandonedLFGDungeon = 123, /*NYI*/                       // Abandoned an LFG dungeon
	MoneySpentOnGuildRepair = 124, /*NYI*/                   // Guild repair amount spent
	GuildAttainedLevel = 125, /*NYI*/                        // Guild attained level
	CreatedItemsByCastingSpell = 126, /*NYI*/                // Created items by casting a spell
	FishInAnyPool = 127, /*NYI*/                             // Fish in any pool
	GuildBankTabsPurchased = 128, /*NYI*/                    // Guild bank tabs purchased
	EarnGuildAchievementPoints = 129, /*NYI*/                // Earn guild achievement points
	WinAnyBattleground = 130, /*NYI*/                        // Win any battleground
	ParticipateInAnyBattleground = 131, /*NYI*/              // Participate in any battleground
	EarnBattlegroundRating = 132, /*NYI*/                    // Earn a battleground rating
	GuildTabardCreated = 133, /*NYI*/                        // Guild tabard created
	CompleteQuestsCountForGuild = 134, /*NYI*/               // Count of complete quests for guild (Quest count)
	HonorableKillsForGuild = 135, /*NYI*/                    // Honorable kills for Guild
	KillAnyCreatureForGuild = 136, /*NYI*/                   // Kill any NPC for Guild
	GroupedTankLeftEarlyInLFGDungeon = 137, /*NYI*/          // Grouped tank left early in an LFG dungeon
	CompleteGuildChallenge = 138, /*NYI*/                    // Complete a "{$Guild Challenge}" guild challenge
	CompleteAnyGuildChallenge = 139, /*NYI*/                 // Complete any guild challenge
	MarkedAFKInBattleground = 140, /*NYI*/                   // Marked AFK in a battleground
	RemovedAFKInBattleground = 141, /*NYI*/                  // Removed for being AFK in a battleground
	StartAnyBattleground = 142, /*NYI*/                      // Start any battleground (AFK tracking)
	CompleteAnyBattleground = 143, /*NYI*/                   // Complete any battleground (AFK tracking)
	MarkedSomeoneAFKInBattleground = 144, /*NYI*/            // Marked someone for being AFK in a battleground
	CompletedLFRDungeon = 145, /*NYI*/                       // Completed an LFR dungeon
	AbandonedLFRDungeon = 146, /*NYI*/                       // Abandoned an LFR dungeon
	KickInitiatorInLFRDungeon = 147, /*NYI*/                 // Kicked in an LFR dungeon (initiator)
	KickVoterInLFRDungeon = 148, /*NYI*/                     // Kicked in an LFR dungeon (voter)
	KickTargetInLFRDungeon = 149, /*NYI*/                    // Kicked in an LFR dungeon (target)
	GroupedTankLeftEarlyInLFRDungeon = 150, /*NYI*/          // Grouped tank left early in an LFR dungeon
	CompleteAnyScenario = 151, /*NYI*/                       // Complete a Scenario
	CompleteScenario = 152, /*NYI*/                          // Complete scenario "{Scenario}"
	EnterAreaTriggerWithActionSet = 153, /*NYI*/             // Enter area trigger "{AreaTriggerActionSet}"
	LeaveAreaTriggerWithActionSet = 154, /*NYI*/             // Leave area trigger "{AreaTriggerActionSet}"
	LearnedNewPet = 155,                                     // (Account Only) Learned a new pet
	UniquePetsOwned = 156,                                   // (Account Only) Unique pets owned
	AccountObtainPetThroughBattle = 157, /*NYI*/             // (Account Only) Obtain a pet through battle
	WinPetBattle = 158, /*NYI*/                              // Win a pet battle
	LosePetBattle = 159, /*NYI*/                             // Lose a pet battle
	BattlePetReachLevel = 160,                               // (Account Only) Battle pet has reached level {#Level}
	PlayerObtainPetThroughBattle = 161, /*NYI*/              // (Player) Obtain a pet through battle
	ActivelyEarnPetLevel = 162,                              // (Player) Actively earn level {#Level} with a pet by a player
	EnterArea = 163, /*NYI*/                                 // Enter Map Area "{AreaTable}"
	LeaveArea = 164, /*NYI*/                                 // Leave Map Area "{AreaTable}"
	DefeatDungeonEncounter = 165, /*NYI*/                    // Defeat Encounter "{DungeonEncounter}"
	PlaceAnyGarrisonBuilding = 166, /*NYI*/                  // Garrison Building: Place any
	PlaceGarrisonBuilding = 167,                             // Garrison Building: Place "{GarrBuilding}"
	ActivateAnyGarrisonBuilding = 168,                       // Garrison Building: Activate any
	ActivateGarrisonBuilding = 169, /*NYI*/                  // Garrison Building: Activate "{GarrBuilding}"
	UpgradeGarrison = 170, /*NYI*/                           // Garrison: Upgrade Garrison to Tier "{#Tier:2,3}"
	StartAnyGarrisonMissionWithFollowerType = 171, /*NYI*/   // Garrison Mission: Start any with FollowerType "{GarrFollowerType}"
	StartGarrisonMission = 172, /*NYI*/                      // Garrison Mission: Start "{GarrMission}"
	SucceedAnyGarrisonMissionWithFollowerType = 173, /*NYI*/ // Garrison Mission: Succeed any with FollowerType "{GarrFollowerType}"
	SucceedGarrisonMission = 174, /*NYI*/                    // Garrison Mission: Succeed "{GarrMission}"
	RecruitAnyGarrisonFollower = 175, /*NYI*/                // Garrison Follower: Recruit any
	RecruitGarrisonFollower = 176,                           // Garrison Follower: Recruit "{GarrFollower}"
	AcquireGarrison = 177, /*NYI*/                           // Garrison: Acquire a Garrison
	LearnAnyGarrisonBlueprint = 178, /*NYI*/                 // Garrison Blueprint: Learn any
	LearnGarrisonBlueprint = 179, /*NYI*/                    // Garrison Blueprint: Learn "{GarrBuilding}"
	LearnAnyGarrisonSpecialization = 180, /*NYI*/            // Garrison Specialization: Learn any
	LearnGarrisonSpecialization = 181, /*NYI*/               // Garrison Specialization: Learn "{GarrSpecialization}"
	CollectGarrisonShipment = 182, /*NYI*/                   // Garrison Shipment of type "{CharShipmentContainer}" collected
	ItemLevelChangedForGarrisonFollower = 183, /*NYI*/       // Garrison Follower: Item Level Changed
	LevelChangedForGarrisonFollower = 184, /*NYI*/           // Garrison Follower: Level Changed
	LearnToy = 185, /*NYI*/                                  // Learn Toy "{Item}"
	LearnAnyToy = 186, /*NYI*/                               // Learn Any Toy
	QualityUpgradedForGarrisonFollower = 187, /*NYI*/        // Garrison Follower: Quality Upgraded
	LearnHeirloom = 188, /*NYI*/                             // Learn Heirloom "{Item}"
	LearnAnyHeirloom = 189, /*NYI*/                          // Learn Any Heirloom
	EarnArtifactXP = 190, /*NYI*/                            // Earn Artifact XP
	AnyArtifactPowerRankPurchased = 191, /*NYI*/             // Artifact Power Ranks Purchased
	LearnTransmog = 192, /*NYI*/                             // Learn Transmog "{ItemModifiedAppearance}"
	LearnAnyTransmog = 193, /*NYI*/                          // Learn Any Transmog
	HonorLevelIncrease = 194,                                // (Player) honor level increase
	PrestigeLevelIncrease = 195, /*NYI*/                     // (Player) prestige level increase
	ActivelyReachLevel = 196,                                // Actively level to level {#Level}
	CompleteResearchAnyGarrisonTalent = 197, /*NYI*/         // Garrison Talent: Complete Research Any
	CompleteResearchGarrisonTalent = 198, /*NYI*/            // Garrison Talent: Complete Research "{GarrTalent}"
	LearnAnyTransmogInSlot = 199,                            // Learn Any Transmog in Slot "{$Equip Slot}"
	RecruitAnyGarrisonTroop = 200, /*NYI*/                   // Recruit any Garrison Troop
	StartResearchAnyGarrisonTalent = 201, /*NYI*/            // Garrison Talent: Start Research Any
	StartResearchGarrisonTalent = 202, /*NYI*/               // Garrison Talent: Start Research "{GarrTalent}"
	CompleteAnyWorldQuest = 203, /*NYI*/                     // Complete Any Quest
	EarnLicense = 204, /*NYI*/                               // Earn License "{BattlePayDeliverable}" (does NOT work for box level)
	CollectTransmogSetFromGroup = 205,                       // (Account Only) Collect a Transmog Set from Group "{TransmogSetGroup}"
	ParagonLevelIncreaseWithFaction = 206, /*NYI*/           // (Player) paragon level increase with faction "{Faction}"
	PlayerHasEarnedHonor = 207, /*NYI*/                      // Player has earned honor
	KillCreatureScenario = 208, /*NYI*/                      // Kill NPC "{Creature}" (scenario criteria only, do not use for player)
	ArtifactPowerRankPurchased = 209, /*NYI*/                // Artifact Power Rank of "{ArtifactPower}" Purchased
	ChooseAnyRelicTalent = 210, /*NYI*/                      // Choose any Relic Talent
	ChooseRelicTalent = 211, /*NYI*/                         // Choose Relic Talent "{ArtifactPower}"
	EarnExpansionLevel = 212, /*NYI*/                        // Earn Expansion Level "{$Expansion Level}"
	AccountHonorLevelReached = 213, /*NYI*/                  // (Account Only) honor level {#Level} reached
	EarnArtifactXPForAzeriteItem = 214,                      // Earn Artifact experience for Azerite Item
	AzeriteLevelReached = 215,                               // Azerite Level {#Azerite Level} reached
	MythicPlusCompleted = 216, /*NYI*/                       // Mythic Plus Completed
	ScenarioGroupCompleted = 217, /*NYI*/                    // Scenario Group Completed
	CompleteAnyReplayQuest = 218,                            // Complete Any Replay Quest
	BuyItemsFromVendors = 219,                               // Buy items from vendors
	SellItemsToVendors = 220,                                // Sell items to vendors
	ReachMaxLevel = 221, /*NYI*/                             // Reach Max Level
	MemorizeSpell = 222, /*NYI*/                             // Memorize Spell "{Spell}"
	LearnTransmogIllusion = 223, /*NYI*/                     // Learn Transmog Illusion
	LearnAnyTransmogIllusion = 224, /*NYI*/                  // Learn Any Transmog Illusion
	EnterTopLevelArea = 225,                                 // Enter Top Level Map Area "{AreaTable}"
	LeaveTopLevelArea = 226, /*NYI*/                         // Leave Top Level Map Area "{AreaTable}"
	SocketGarrisonTalent = 227, /*NYI*/                      // Socket Garrison Talent {GarrTalent}
	SocketAnySoulbindConduit = 228, /*NYI*/                  // Socket Any Soulbind Conduit
	ObtainAnyItemWithCurrencyValue = 229, /*NYI*/            // Obtain Any Item With Currency Value "{CurrencyTypes}"
	MythicPlusRatingAttained = 230, /*NYI*/                  // (Player) Mythic+ Rating "{#DungeonScore}" attained
	SpentTalentPoint = 231, /*NYI*/                          // (Player) spent talent point
	MythicPlusDisplaySeasonEnded = 234, /*NYI*/              // {DisplaySeason}
	WinRatedSoloShuffleRound = 239,                          /*NYI*/
	ParticipateInRatedSoloShuffleRound = 240,                /*NYI*/
	ReputationAmountGained = 243, /*NYI*/                    // Gain reputation amount with {FactionID}; accumulate, not highest
	FulfillAnyCraftingOrder = 245,                           /*NYI*/
	FulfillCraftingOrderType = 246, /*NYI*/                  // {CraftingOrderType}

	PerksProgramMonthComplete = 249, /*NYI*/

	Count
}