// Copyright (c) Forged WoW LLC <https://github.com/ForgedWoW/ForgedCore>
// Licensed under GPL-3.0 license. See <https://github.com/ForgedWoW/ForgedCore/blob/master/LICENSE> for full information.

namespace Framework.Constants;

public enum ChatMsg
{
    Addon = -1,
    System = 0x00,
    Say = 0x01,
    Party = 0x02,
    Raid = 0x03,
    Guild = 0x04,
    Officer = 0x05,
    Yell = 0x06,
    Whisper = 0x07,
    WhisperForeign = 0x08,
    WhisperInform = 0x09,
    Emote = 0x0a,
    TextEmote = 0x0b,
    MonsterSay = 0x0c,
    MonsterParty = 0x0d,
    MonsterYell = 0x0e,
    MonsterWhisper = 0x0f,
    MonsterEmote = 0x10,
    Channel = 0x11,
    ChannelJoin = 0x12,
    ChannelLeave = 0x13,
    ChannelList = 0x14,
    ChannelNotice = 0x15,
    ChannelNoticeUser = 0x16,
    Afk = 0x17,
    Dnd = 0x18,
    Ignored = 0x19,
    Skill = 0x1a,
    Loot = 0x1b,
    Money = 0x1c,
    Opening = 0x1d,
    Tradeskills = 0x1e,
    PetInfo = 0x1f,
    CombatMiscInfo = 0x20,
    CombatXpGain = 0x21,
    CombatHonorGain = 0x22,
    CombatFactionChange = 0x23,
    BgSystemNeutral = 0x24,
    BgSystemAlliance = 0x25,
    BgSystemHorde = 0x26,
    RaidLeader = 0x27,
    RaidWarning = 0x28,
    RaidBossEmote = 0x29,
    RaidBossWhisper = 0x2a,
    Filtered = 0x2b,
    Restricted = 0x2c,
    Battlenet = 0x2d,
    Achievement = 0x2e,
    GuildAchievement = 0x2f,
    ArenaPoints = 0x30,
    PartyLeader = 0x31,
    Targeticons = 0x32,
    BnWhisper = 0x33,
    BnWhisperInform = 0x34,
    BnInlineToastAlert = 0x35,
    BnInlineToastBroadcast = 0x36,
    BnInlineToastBroadcastInform = 0x37,
    BnInlineToastConversation = 0x38,
    BnWhisperPlayerOffline = 0x39,
    Currency = 0x3a,
    QuestBossEmote = 0x3b,
    PetBattleCombatLog = 0x3c,
    PetBattleInfo = 0x3d,
    InstanceChat = 0x3e,
    InstanceChatLeader = 0x3f,
    GuildItemLooted = 0x40,
    CommunitiesChannel = 0x41,
    VoiceText = 0x42,
    Max
}