// Copyright (c) Forged WoW LLC <https://github.com/ForgedWoW/ForgedCore>
// Licensed under GPL-3.0 license. See <https://github.com/ForgedWoW/ForgedCore/blob/master/LICENSE> for full information.

namespace Framework.Constants;

public enum HolidayIds
{
    None = 0,
    FireworksSpectacular = 62,
    FeastOfWinterVeil = 141,
    Noblegarden = 181,
    ChildrensWeek = 201,
    CallToArmsAvOld = 283,
    CallToArmsWgOld = 284,
    CallToArmsAbOld = 285,
    HarvestFestival = 321,
    HallowsEnd = 324,
    LunarFestival = 327,
    LoveIsInTheAirOld = 335,
    MidsummerFireFestival = 341,
    CallToArmsEsOld = 353,
    Brewfest = 372,
    PiratesDay = 398,
    CallToArmsSaOld = 400,
    PilgrimsBounty = 404,
    LkLaunch = 406,
    DayOfTheDead = 409,
    CallToArmsIcOld = 420,
    LoveIsInTheAir = 423,
    KaluAkFishingDerby = 424,
    CallToArmsBg = 435,
    CallToArmsTp = 436,
    RatedBg15Vs15 = 442,
    RatedBg25Vs25 = 443,
    Wow7thAnniversary = 467,
    DarkmoonFaire = 479,
    Wow8thAnniversary = 484,
    CallToArmsSm = 488,
    CallToArmsTk = 489,
    CallToArmsAv = 490,
    CallToArmsAb = 491,
    CallToArmsEs = 492,
    CallToArmsIc = 493,
    CallToArmsSmOld = 494,
    CallToArmsSa = 495,
    CallToArmsTkOld = 496,
    CallToArmsBgOld = 497,
    CallToArmsTpOld = 498,
    CallToArmsWg = 499,
    Wow9thAnniversary = 509,
    Wow10thAnniversary = 514,
    CallToArmsDg = 515,
    CallToArmsDgOld = 516,
    TimewalkingDungeonEventBcDefault = 559,
    ApexisBonusEventDefault = 560,
    ArenaSkirmishBonusEvent = 561,
    TimewalkingDungeonEventLkDefault = 562,
    BattlegroundBonusEventDefault = 563,
    DraenorDungeonEventDefault = 564,
    PetBattleBonusEventDefault = 565,
    Wow11thAnniversary = 566,
    TimewalkingDungeonEventCataDefault = 587,
    Wow12thAnniversary = 589,
    WowAnniversary = 590,
    LegionDungeonEventDefault = 591,
    WorldQuestBonusEventDefault = 592,
    ApexisBonusEventEu = 593,
    ApexisBonusEventTwCn = 594,
    ApexisBonusEventKr = 595,
    DraenorDungeonEventEu = 596,
    DraenorDungeonEventTwCn = 597,
    DraenorDungeonEventKr = 598,
    PetBattleBonusEventEu = 599,
    PetBattleBonusEventTwCn = 600,
    PetBattleBonusEventKr = 601,
    BattlegroundBonusEventEu = 602,
    BattlegroundBonusEventTwCn = 603,
    BattlegroundBonusEventKr = 604,
    LegionDungeonEventEu = 605,
    LegionDungeonEventTwCn = 606,
    LegionDungeonEventKr = 607,
    ArenaSkirmishBonusEventEu = 610,
    ArenaSkirmishBonusEventTwCn = 611,
    ArenaSkirmishBonusEventKr = 612,
    WorldQuestBonusEventEu = 613,
    WorldQuestBonusEventTwCn = 614,
    WorldQuestBonusEventKr = 615,
    TimewalkingDungeonEventLkEu = 616,
    TimewalkingDungeonEventLkTwCn = 617,
    TimewalkingDungeonEventLkKr = 618,
    TimewalkingDungeonEventBcEu = 622,
    TimewalkingDungeonEventBcTwCn = 623,
    TimewalkingDungeonEventBcKr = 624,
    TimewalkingDungeonEventCataEu = 628,
    TimewalkingDungeonEventCataTwCn = 629,
    TimewalkingDungeonEventCataKr = 630,
    HatchingOfTheHippogryphs = 634,
    VolunteerGuardDay = 635,
    CallOfTheScarab = 638,
    ThousandBoatBash = 642,
    TimewalkingDungeonEventMopDefault = 643,
    UngoroMadness = 644,
    SpringBalloonFestival = 645,
    KirinTorTavernCrawl = 646,
    MarchOfTheTadpoles = 647,
    GlowcapFestival = 648,
    TimewalkingDungeonEventMopEu = 652,
    TimewalkingDungeonEventMopTwCn = 654,
    TimewalkingDungeonEventMopKr = 656,
    FireworksCelebration = 658,
    PvpBrawlGl1984 = 659,
    PvpBrawlSsVsTm1984 = 660,
    PvpBrawlSsVsTmUs = 662,
    PvpBrawlGlUs = 663,
    PvpBrawlWsUs = 664,
    PvpBrawlAbUs = 666,
    PvpBrawlPhUs = 667,
    PvpBrawlSsVsTmEu = 669,
    PvpBrawlGlEu = 670,
    PvpBrawlWsEu = 671,
    PvpBrawlAbEu = 673,
    PvpBrawlPhEu = 674,
    PvpBrawlSsVsTmTwCn = 676,
    PvpBrawlGlTwCn = 677,
    PvpBrawlWsTwCn = 678,
    PvpBrawlAbTwCn = 680,
    PvpBrawlPhTwCn = 681,
    PvpBrawlSsVsTmKr = 683,
    PvpBrawlGlKr = 684,
    PvpBrawlWsKr = 685,
    PvpBrawlAbKr = 687,
    PvpBrawlPhKr = 688,
    TrialOfStyle = 691,
    AuctionHouseDanceParty = 692,
    Wow13thAnniversary = 693,
    MookinFestival = 694,
    TheGreatGnomereganRun = 696,
    PvpBrawlWs1984 = 701,
    PvpBrawlDsUs = 702,
    PvpBrawlDsEu = 704,
    PvpBrawlDsTwCn = 705,
    PvpBrawlDsKr = 706,
    TombOfSargerasNormalHeroicDefault = 710,   // Tomb Of Sargeras: Kil'Jaeden Awaits!
    TombOfSargerasNormalHeroicEu = 711,        // Tomb Of Sargeras: Kil'Jaeden Awaits!
    TombOfSargerasNormalHeroicTwCn = 712,      // Tomb Of Sargeras: Kil'Jaeden Awaits!
    TombOfSargerasNormalHeroicKr = 713,        // Tomb Of Sargeras: Kil'Jaeden Awaits!
    TombOfSargerasRf1SectionDefault = 714,     // Tomb Of Sargeras: The Gates Of Hell.
    TombOfSargerasRf1SectionEu = 715,          // Tomb Of Sargeras: The Gates Of Hell.
    TombOfSargerasRf1SectionTwCn = 716,        // Tomb Of Sargeras: The Gates Of Hell.
    TombOfSargerasRf1SectionKr = 717,          // Tomb Of Sargeras: The Gates Of Hell.
    TombOfSargerasRf2SectionDefault = 718,     // Tomb Of Sargeras: Wailing Halls.
    TombOfSargerasRf2SectionEu = 719,          // Tomb Of Sargeras: Wailing Halls.
    TombOfSargerasRf2SectionTwCn = 720,        // Tomb Of Sargeras: Wailing Halls.
    TombOfSargerasRf2SectionKr = 721,          // Tomb Of Sargeras: Wailing Halls.
    TombOfSargerasRf3SectionDefault = 722,     // Tomb Of Sargeras: Chamber Of The Avatar.
    TombOfSargerasRf3SectionEu = 723,          // Tomb Of Sargeras: Chamber Of The Avatar.
    TombOfSargerasRf3SectionTwCn = 724,        // Tomb Of Sargeras: Chamber Of The Avatar.
    TombOfSargerasRf3SectionKr = 725,          // Tomb Of Sargeras: Chamber Of The Avatar.
    TombOfSargerasFinalEncounterDefault = 726, // Tomb Of Sargeras: Deceiver'S Fall. Kil'Jaeden Awaits!
    TombOfSargerasFinalEncounterEu = 727,      // Tomb Of Sargeras: Deceiver'S Fall. Kil'Jaeden Awaits!
    TombOfSargerasFinalEncounterTwCn = 728,    // Tomb Of Sargeras: Deceiver'S Fall. Kil'Jaeden Awaits!
    TombOfSargerasFinalEncounterKr = 729,      // Tomb Of Sargeras: Deceiver'S Fall. Kil'Jaeden Awaits!
    TombOfSargerasNormalHeroic768 = 730,       // Tomb Of Sargeras: Kil'Jaeden Awaits!
    PvpBrawlDs1984 = 736,
    PvpBrawlAb1984 = 737,
    ShadowsOfArgusWeek2UnlocksDefault = 744,       // In Part 2 Of Shadows Of Argus, Finish The Story Of Krokuun And Travel To The Ruined Draenei City Of Mac'Aree. Gain Access To Invasion Points And Thwart The Burning Legion'S Plans On Other Worlds. Additional World Quests Become Available.
    ShadowsOfArgusWeek3UnlocksDefault = 745,       // In Part 3 Of Shadows Of Argus, Finish The Shadows Of Argus Storyline, Unlock All World Quests, And Venture Into The New Dungeon, The Seat Of The Triumvirate. Activate Your Netherlight Crucible On The Vindicaar To Begin Forging Relics.
    ShadowsOfArgusWeek2UnlocksKr = 746,            // In Part 2 Of Shadows Of Argus, Finish The Story Of Krokuun And Travel To The Ruined Draenei City Of Mac'Aree. Gain Access To Invasion Points And Thwart The Burning Legion'S Plans On Other Worlds. Additional World Quests Become Available.
    ShadowsOfArgusWeek2UnlocksEu = 747,            // In Part 2 Of Shadows Of Argus, Finish The Story Of Krokuun And Travel To The Ruined Draenei City Of Mac'Aree. Gain Access To Invasion Points And Thwart The Burning Legion'S Plans On Other Worlds. Additional World Quests Become Available.
    ShadowsOfArgusWeek2UnlocksTwCn = 748,          // In Part 2 Of Shadows Of Argus, Finish The Story Of Krokuun And Travel To The Ruined Draenei City Of Mac'Aree. Gain Access To Invasion Points And Thwart The Burning Legion'S Plans On Other Worlds. Additional World Quests Become Available.
    ShadowsOfArgusWeek3UnlocksTwCn = 749,          // In Part 3 Of Shadows Of Argus, Finish The Shadows Of Argus Storyline, Unlock All World Quests, And Venture Into The New Dungeon, The Seat Of The Triumvirate. Activate Your Netherlight Crucible On The Vindicaar To Begin Forging Relics.
    ShadowsOfArgusWeek3UnlocksKr = 750,            // In Part 3 Of Shadows Of Argus, Finish The Shadows Of Argus Storyline, Unlock All World Quests, And Venture Into The New Dungeon, The Seat Of The Triumvirate. Activate Your Netherlight Crucible On The Vindicaar To Begin Forging Relics.
    ShadowsOfArgusWeek3UnlocksEu = 751,            // In Part 3 Of Shadows Of Argus, Finish The Shadows Of Argus Storyline, Unlock All World Quests, And Venture Into The New Dungeon, The Seat Of The Triumvirate. Activate Your Netherlight Crucible On The Vindicaar To Begin Forging Relics.
    AntorusBurningThroneRf2SectionTwCn = 756,      // Antorus, The Burning Throne: Forbidden Descent.
    AntorusBurningThroneRf2SectionEu = 757,        // Antorus, The Burning Throne: Forbidden Descent.
    AntorusBurningThroneRf2SectionKr = 758,        // Antorus, The Burning Throne: Forbidden Descent.
    AntorusBurningThroneRf2SectionDefault = 759,   // Antorus, The Burning Throne: Forbidden Descent.
    AntorusBurningThroneRf3SectionTwCn = 760,      // Antorus, The Burning Throne: Hope'S End.
    AntorusBurningThroneRf3SectionEu = 761,        // Antorus, The Burning Throne: Hope'S End.
    AntorusBurningThroneRf3SectionKr = 762,        // Antorus, The Burning Throne: Hope'S End.
    AntorusBurningThroneRf3SectionDefault = 763,   // Antorus, The Burning Throne: Hope'S End.
    AntorusBurningThroneFinalSectionTwCn = 764,    // Antorus, The Burning Throne: Seat Of The Pantheon.
    AntorusBurningThroneFinalSectionEu = 765,      // Antorus, The Burning Throne: Seat Of The Pantheon.
    AntorusBurningThroneFinalSectionKr = 766,      // Antorus, The Burning Throne: Seat Of The Pantheon.
    AntorusBurningThroneFinalSectionDefault = 767, // Antorus, The Burning Throne: Seat Of The Pantheon.
    AntorusBurningThroneRf1SectionTwCn = 768,      // Antorus, The Burning Throne: Light'S Breach.
    AntorusBurningThroneRf1SectionEu = 769,        // Antorus, The Burning Throne: Light'S Breach.
    AntorusBurningThroneRf1SectionKr = 770,        // Antorus, The Burning Throne: Light'S Breach.
    AntorusBurningThroneRf1SectionDefault = 771,   // Antorus, The Burning Throne: Light'S Breach.
    AntorusBurningThroneNormalHeroicTwCn = 772,    // Antorus, The Burning Throne: Argus Awaits!
    AntorusBurningThroneNormalHeroicEu = 773,      // Antorus, The Burning Throne: Argus Awaits!
    AntorusBurningThroneNormalHeroicKr = 774,      // Antorus, The Burning Throne: Argus Awaits!
    AntorusBurningThroneNormalHeroicDefault = 775, // Antorus, The Burning Throne: Argus Awaits!
    AntorusBurningThroneNormalHeroic768 = 776,     // Antorus, The Burning Throne: Argus Awaits!
    Wow14thAnniversary = 807,
    Wow15thAnniversary = 808,
    WarOfTheThorns = 918,           // Conflict Emerges In Darkshore As The Horde And Alliance Battle For Control Over Teldrassil In This Limited Time Event!
    UldirNormalHeroic768 = 920,     // Uldir: G'Huun Awaits!
    UldirNormalHeroicDefault = 921, // Uldir: G'Huun Awaits!
    UldirNormalHeroicKr = 922,      // Uldir: G'Huun Awaits!
    UldirNormalHeroicEu = 923,      // Uldir: G'Huun Awaits!
    UldirNormalHeroicTwCn = 924,    // Uldir: G'Huun Awaits!
    UldirRf1SectionDefault = 925,   // Uldir: Halls Of Containment.
    UldirRf1SectionKr = 926,        // Uldir: Halls Of Containment.
    UldirRf1SectionEu = 927,        // Uldir: Halls Of Containment.
    UldirRf1SectionTwCn = 928,      // Uldir: Halls Of Containment.
    UldirRf2SectionDefault = 929,   // Uldir: Crimson Descent.
    UldirRf2SectionKr = 930,        // Uldir: Crimson Descent.
    UldirRf2SectionEu = 931,        // Uldir: Crimson Descent.
    UldirRf2SectionTwCn = 932,      // Uldir: Crimson Descent.
    UldirFinalSectionDefault = 933, // Uldir: Heart Of Corruption.
    UldirFinalSectionKr = 934,      // Uldir: Heart Of Corruption.
    UldirFinalSectionEu = 935,      // Uldir: Heart Of Corruption.
    UldirFinalSectionTwCn = 936,    // Uldir: Heart Of Corruption.
    BattleForAzerothDungeonEventEu = 938,
    BattleForAzerothDungeonEventTwCn = 939,
    BattleForAzerothDungeonEventKr = 940,
    BattleForAzerothDungeonEventDefault = 941,
    WarOfTheThornsEu = 956,                      // Conflict Emerges In Darkshore As The Horde And Alliance Battle For Control Over Teldrassil In This Limited Time Event!
    WarOfTheThornsTwCn = 957,                    // Conflict Emerges In Darkshore As The Horde And Alliance Battle For Control Over Teldrassil In This Limited Time Event!
    WarOfTheThornsKr = 958,                      // Conflict Emerges In Darkshore As The Horde And Alliance Battle For Control Over Teldrassil In This Limited Time Event!
    WarOfTheThorns320 = 959,                     // Conflict Emerges In Darkshore As The Horde And Alliance Battle For Control Over Teldrassil In This Limited Time Event!
    WarOfTheThornsUs = 965,                      // Conflict Emerges In Darkshore As The Horde And Alliance Battle For Control Over Teldrassil In This Limited Time Event!
    WarOfTheThorns512 = 967,                     // Conflict Emerges In Darkshore As The Horde And Alliance Battle For Control Over Teldrassil In This Limited Time Event!
    WarOfTheThorns128 = 973,                     // Conflict Emerges In Darkshore As The Horde And Alliance Battle For Control Over Teldrassil In This Limited Time Event!
    UldirNormalHeroic = 979,                     // Uldir: G'Huun Awaits!
    BattleOfDazaralorNormalHeroicDefault = 1025, // Battle Of Dazar'Alor Raid
    BattleOfDazaralorNormalHeroicKr = 1026,      // Battle Of Dazar'Alor Raid
    BattleOfDazaralorNormalHeroicEu = 1027,      // Battle Of Dazar'Alor Raid
    BattleOfDazaralorNormalHeroicTwCn = 1028,    // Battle Of Dazar'Alor Raid
    BattleOfDazaralorNormalHeroic768 = 1029,     // Battle Of Dazar'Alor Raid
    BattleOfDazaralorRf1SectionDefault = 1030,   // Battle Of Dazar'Alor: Siege Of Dazar'Alor.
    BattleOfDazaralorRf1SectionKr = 1031,        // Battle Of Dazar'Alor: Siege Of Dazar'Alor.
    BattleOfDazaralorRf1SectionEu = 1032,        // Battle Of Dazar'Alor: Siege Of Dazar'Alor.
    BattleOfDazaralorRf1SectionTwCn = 1033,      // Battle Of Dazar'Alor: Siege Of Dazar'Alor.
    BattleOfDazaralorRf2SectionDefault = 1034,   // Battle Of Dazar'Alor: Empire'S Fall.
    BattleOfDazaralorRf2SectionKr = 1035,        // Battle Of Dazar'Alor: Empire'S Fall.
    BattleOfDazaralorRf2SectionEu = 1036,        // Battle Of Dazar'Alor: Empire'S Fall.
    BattleOfDazaralorRf2SectionTwCn = 1037,      // Battle Of Dazar'Alor: Empire'S Fall.
    BattleOfDazaralorRf3SectionDefault = 1038,   // Battle Of Dazar'Alor: Might Of The Alliance For Alliance Players, And Victory Or Death For Horde Players.
    BattleOfDazaralorRf3SectionKr = 1039,        // Battle Of Dazar'Alor: Might Of The Alliance For Alliance Players, And Victory Or Death For Horde Players.
    BattleOfDazaralorRf3SectionEu = 1040,        // Battle Of Dazar'Alor: Might Of The Alliance For Alliance Players, And Victory Or Death For Horde Players.
    BattleOfDazaralorRf3SectionTwCn = 1041,      // Battle Of Dazar'Alor: Might Of The Alliance For Alliance Players, And Victory Or Death For Horde Players.
    PvpBrawlCookingImpossibleUs = 1047,
    PvpBrawlCookingImpossibleKr = 1048,
    PvpBrawlCookingImpossibleEu = 1049,
    PvpBrawlCookingImpossible1984 = 1050,
    PvpBrawlCookingImpossibleTwCn = 1051,
    WanderersFestival = 1052,
    FreeTshirtDay = 1053,
    LuminousLuminaries = 1054,
    TimewalkingDungeonEventWodDefault = 1056,
    LuminousLuminaries64 = 1062,
    TimewalkingDungeonEventWodEu = 1063,
    TimewalkingDungeonEventWodKr = 1065,
    TimewalkingDungeonEventWodTwCn = 1068,
    CrucibleOfStormsNormalHeroicDefault = 1069, // Delve Into The Chambers Beneath Stormsong Valley To Uncover The Source Of The Shadow Spreading Across The Land, Now Available On Normal Or Heroic Difficulty.
    CrucibleOfStormsNormalHeroicKr = 1070,      // Delve Into The Chambers Beneath Stormsong Valley To Uncover The Source Of The Shadow Spreading Across The Land, Now Available On Normal Or Heroic Difficulty.
    CrucibleOfStormsNormalHeroicEu = 1071,      // Delve Into The Chambers Beneath Stormsong Valley To Uncover The Source Of The Shadow Spreading Across The Land, Now Available On Normal Or Heroic Difficulty.
    CrucibleOfStormsNormalHeroicTwCn = 1072,    // Delve Into The Chambers Beneath Stormsong Valley To Uncover The Source Of The Shadow Spreading Across The Land, Now Available On Normal Or Heroic Difficulty.
    CrucibleOfStormsNormalHeroic = 1073,        // Delve Into The Chambers Beneath Stormsong Valley To Uncover The Source Of The Shadow Spreading Across The Land, Now Available On Normal Or Heroic Difficulty.
    CrucibleOfStormsRaidFinderDefault = 1074,   // Mythic Difficulty Of The Crucible Of Storms Raid Awaits The Boldest Of Adventurers, And Players May Now Use The Raid Finder To Access The Raid.
    CrucibleOfStormsRaidFinderEu = 1075,        // Mythic Difficulty Of The Crucible Of Storms Raid Awaits The Boldest Of Adventurers, And Players May Now Use The Raid Finder To Access The Raid.
    CrucibleOfStormsRaidFinderKr = 1076,        // Mythic Difficulty Of The Crucible Of Storms Raid Awaits The Boldest Of Adventurers, And Players May Now Use The Raid Finder To Access The Raid.
    CrucibleOfStormsRaidFinderTwCn = 1077,      // Mythic Difficulty Of The Crucible Of Storms Raid Awaits The Boldest Of Adventurers, And Players May Now Use The Raid Finder To Access The Raid.
    CrucibleOfStormsRaidFinder = 1078,          // Mythic Difficulty Of The Crucible Of Storms Raid Awaits The Boldest Of Adventurers, And Players May Now Use The Raid Finder To Access The Raid.
    TheEternalPalaceDefault = 1098,             // The Dangers Of Nazjatar Were Merely Preamble. Breach The Palace Gates And Descend Into Azshara'S Deadly Domain.
    TheEternalPalaceKr = 1099,                  // The Dangers Of Nazjatar Were Merely Preamble. Breach The Palace Gates And Descend Into Azshara'S Deadly Domain.
    TheEternalPalaceEu = 1100,                  // The Dangers Of Nazjatar Were Merely Preamble. Breach The Palace Gates And Descend Into Azshara'S Deadly Domain.
    TheEternalPalaceTwCn = 1101,                // The Dangers Of Nazjatar Were Merely Preamble. Breach The Palace Gates And Descend Into Azshara'S Deadly Domain.
    TheEternalPalaceRaidFinderDefault = 1102,   // Mythic Difficulty Of The Eternal Palace Raid Awaits The Boldest Of Adventurers, And Players May Now Use The Raid Finder To Access The Raid.
    TheEternalPalaceRaidFinderKr = 1103,        // Mythic Difficulty Of The Eternal Palace Raid Awaits The Boldest Of Adventurers, And Players May Now Use The Raid Finder To Access The Raid.
    TheEternalPalaceRaidFinderEu = 1104,        // Mythic Difficulty Of The Eternal Palace Raid Awaits The Boldest Of Adventurers, And Players May Now Use The Raid Finder To Access The Raid.
    TheEternalPalaceRaidFinderTwCn = 1105,      // Mythic Difficulty Of The Eternal Palace Raid Awaits The Boldest Of Adventurers, And Players May Now Use The Raid Finder To Access The Raid.
    TheEternalPalaceRf2SectionEu = 1106,        // The Eternal Palace: Depths Of The Devoted.
    TheEternalPalaceRf2SectionTwCn = 1107,      // The Eternal Palace: Depths Of The Devoted.
    TheEternalPalaceFinalSectionDefault = 1108, // The Eternal Palace: The Circle Of Stars.
    TheEternalPalaceFinalSectionKr = 1109,      // The Eternal Palace: The Circle Of Stars.
    TheEternalPalaceFinalSectionEu = 1110,      // The Eternal Palace: The Circle Of Stars.
    TheEternalPalaceFinalSectionTwCn = 1111,    // The Eternal Palace: The Circle Of Stars.
    TheEternalPalaceRf2SectionKr = 1112,        // The Eternal Palace: Depths Of The Devoted.
    TheEternalPalaceRf2SectionDefault = 1113,   // The Eternal Palace: Depths Of The Devoted.
    PvpBrawlClassicAshranUs = 1120,
    PvpBrawlClassicAshranKr = 1121,
    PvpBrawlClassicAshranEu = 1122,
    PvpBrawlClassicAshran1984 = 1123,
    PvpBrawlClassicAshranTwCn = 1124,
    NyalothaWalkingCityDefault = 1140,             // Descend Into Ny'Alotha, The Waking City And Face N'Zoth In His Own Realm.
    NyalothaWalkingCityKr = 1141,                  // Descend Into Ny'Alotha, The Waking City And Face N'Zoth In His Own Realm.
    NyalothaWalkingCityEu = 1142,                  // Descend Into Ny'Alotha, The Waking City And Face N'Zoth In His Own Realm.
    NyalothaWalkingCityTwCn = 1143,                // Descend Into Ny'Alotha, The Waking City And Face N'Zoth In His Own Realm.
    NyalothaWalkingCityRaidFinderDefault = 1144,   // Mythic Difficulty Of Ny'Alotha, The Waking City Awaits The Boldest Of Adventurers, And Players May Now Use The Raid Finder To Access The Raid.
    NyalothaWalkingCityRaidFinderKr = 1145,        // Mythic Difficulty Of Ny'Alotha, The Waking City Awaits The Boldest Of Adventurers, And Players May Now Use The Raid Finder To Access The Raid.
    NyalothaWalkingCityRaidFinderEu = 1146,        // Mythic Difficulty Of Ny'Alotha, The Waking City Awaits The Boldest Of Adventurers, And Players May Now Use The Raid Finder To Access The Raid.
    NyalothaWalkingCityRaidFinderTwCn = 1147,      // Mythic Difficulty Of Ny'Alotha, The Waking City Awaits The Boldest Of Adventurers, And Players May Now Use The Raid Finder To Access The Raid.
    NyalothaWalkingCityRf2SectionDefault = 1148,   // Ny'Alotha, The Waking City: Halls Of Devotion.
    NyalothaWalkingCityRf2SectionKr = 1149,        // Ny'Alotha, The Waking City: Halls Of Devotion.
    NyalothaWalkingCityRf2SectionEu = 1150,        // Ny'Alotha, The Waking City: Halls Of Devotion.
    NyalothaWalkingCityRf2SectionTwCn = 1151,      // Ny'Alotha, The Waking City: Halls Of Devotion.
    NyalothaWalkingCityRf3SectionDefault = 1152,   // Ny'Alotha, The Waking City: Gift Of Flesh.
    NyalothaWalkingCityRf3SectionKr = 1153,        // Ny'Alotha, The Waking City: Gift Of Flesh.
    NyalothaWalkingCityRf3SectionEu = 1154,        // Ny'Alotha, The Waking City: Gift Of Flesh.
    NyalothaWalkingCityRf3SectionTwCn = 1155,      // Ny'Alotha, The Waking City: Gift Of Flesh.
    NyalothaWalkingCityFinalSectionDefault = 1156, // Ny'Alotha, The Waking City: The Waking Dream.
    NyalothaWalkingCityFinalSectionKr = 1157,      // Ny'Alotha, The Waking City: The Waking Dream.
    NyalothaWalkingCityFinalSectionEu = 1158,      // Ny'Alotha, The Waking City: The Waking Dream.
    NyalothaWalkingCityFinalSectionTwCn = 1159,    // Ny'Alotha, The Waking City: The Waking Dream.
    PvpBrawlTh1984 = 1166,
    PvpBrawlThKr = 1167,
    PvpBrawlThTwCn = 1168,
    PvpBrawlThEu = 1169,
    PvpBrawlThUs = 1170,
    Wow16thAnniversary = 1181,
    CastleNathriaDefault = 1194,             // Enter Castle Nathria And Confront Sire Denathrius In His Citadel.
    CastleNathriaRf1SectionDefault = 1195,   // Castle Nathria: The Leeching Vaults.
    CastleNathriaRf2SectionDefault = 1196,   // Castle Nathria: Reliquary Of Opulence.
    CastleNathriaRf3SectionDefault = 1197,   // Castle Nathria: Blood From Stone.
    CastleNathriaEu = 1198,                  // Enter Castle Nathria And Confront Sire Denathrius In His Citadel.
    CastleNathriaRf1SectionEu = 1199,        // Castle Nathria: The Leeching Vaults.
    CastleNathriaRf2SectionEu = 1200,        // Castle Nathria: Reliquary Of Opulence.
    CastleNathriaRf3SectionEu = 1201,        // Castle Nathria: Blood From Stone.
    CastleNathriaKr = 1202,                  // Enter Castle Nathria And Confront Sire Denathrius In His Citadel.
    CastleNathriaRf1SectionKr = 1203,        // Castle Nathria: The Leeching Vaults.
    CastleNathriaRf2SectionKr = 1204,        // Castle Nathria: Reliquary Of Opulence.
    CastleNathriaRf3SectionKr = 1205,        // Castle Nathria: Blood From Stone.
    CastleNathriaTwCn = 1206,                // Enter Castle Nathria And Confront Sire Denathrius In His Citadel.
    CastleNathriaRf1SectionTwCn = 1207,      // Castle Nathria: The Leeching Vaults.
    CastleNathriaRf2SectionTwCn = 1208,      // Castle Nathria: Reliquary Of Opulence.
    CastleNathriaRf3SectionTwCn = 1209,      // Castle Nathria: Blood From Stone.
    CastleNathriaFinalSectionDefault = 1210, // Castle Nathria: An Audience With Arrogance.
    CastleNathriaFinalSectionEu = 1211,      // Castle Nathria: An Audience With Arrogance.
    CastleNathriaFinalSectionKr = 1212,      // Castle Nathria: An Audience With Arrogance.
    CastleNathriaFinalSectionTwCn = 1213,    // Castle Nathria: An Audience With Arrogance.
    TorghastBeastsOfProdigum = 1214,
    TorghastUnbridledDarkness = 1215,
    TorghastChorusOfDeadSouls = 1216,
    ShadowlandsDungeonEventDefault = 1217,
    ShadowlandsDungeonEventEu = 1218,
    ShadowlandsDungeonEventTwCn = 1219,
    ShadowlandsDungeonEventKr = 1220,
    PvpBrawlWs19842 = 1221,
    CastleNathria32 = 1222 // Enter Castle Nathria And Confront Sire Denathrius In His Citadel.
}