// Copyright (c) Forged WoW LLC <https://github.com/ForgedWoW/ForgedCore>
// Licensed under GPL-3.0 license. See <https://github.com/ForgedWoW/ForgedCore/blob/master/LICENSE> for full information.

namespace Framework.Constants;

public enum SpellCustomErrors
{
    None = 0,
    CustomMsg = 1,                                                                      // Something Bad Happened, And We Want To Display A Custom Message!
    AlexBrokeQuest = 2,                                                                 // Alex Broke Your Quest! Thank Him Later!
    NeedHelplessVillager = 3,                                                           // This Spell May Only Be Used On Helpless Wintergarde Villagers That Have Not Been Rescued.
    NeedWarsongDisguise = 4,                                                            // Requires That You Be Wearing The Warsong Orc Disguise.
    RequiresPlagueWagon = 5,                                                            // You Must Be Closer To A Plague Wagon In Order To Drop Off Your 7th Legion Siege Engineer.
    CantTargetFriendlyNonparty = 6,                                                     // You Cannot Target Friendly Units Outside Your Party.
    NeedChillNymph = 7,                                                                 // You Must Target A Weakened Chill Nymph.
    MustBeInEnkilah = 8,                                                                // The Imbued Scourge Shroud Will Only Work When Equipped In The Temple City Of En'Kilah.
    RequiresCorpseDust = 9,                                                             // Requires Corpse Dust
    CantSummonGargoyle = 10,                                                            // You Cannot Summon Another Gargoyle Yet.
    NeedCorpseDustIfNoTarget = 11,                                                      // Requires Corpse Dust If The Target Is Not Dead And Humanoid.
    MustBeAtShatterhorn = 12,                                                           // Can Only Be Placed Near Shatterhorn
    MustTargetProtoDrakeEgg = 13,                                                       // You Must First Select A Proto-Drake Egg.
    MustBeCloseToTree = 14,                                                             // You Must Be Close To A Marked Tree.
    MustTargetTurkey = 15,                                                              // You Must Target A Fjord Turkey.
    MustTargetHawk = 16,                                                                // You Must Target A Fjord Hawk.
    TooFarFromBouy = 17,                                                                // You Are Too Far From The Bouy.
    MustBeCloseToOilSlick = 18,                                                         // Must Be Used Near An Oil Slick.
    MustBeCloseToBouy = 19,                                                             // You Must Be Closer To The Buoy!
    WyrmrestVanquisher = 20,                                                            // You May Only Call For The Aid Of A Wyrmrest Vanquisher In Wyrmrest Temple, The Dragon Wastes, Galakrond'S Rest Or The Wicked Coil.
    MustTargetIceHeartJormungar = 21,                                                   // That Can Only Be Used On A Ice Heart Jormungar Spawn.
    MustBeCloseToSinkhole = 22,                                                         // You Must Be Closer To A Sinkhole To Use Your Map.
    RequiresHaroldLane = 23,                                                            // You May Only Call Down A Stampede On Harold Lane.
    RequiresGammothMagnataur = 24,                                                      // You May Only Use The Pouch Of Crushed Bloodspore On Gammothra Or Other Magnataur In The Bloodspore Plains And Gammoth.
    MustBeInResurrectionChamber = 25,                                                   // Requires The Magmawyrm Resurrection Chamber In The Back Of The Maw Of Neltharion.
    CantCallWintergardeHere = 26,                                                       // You May Only Call Down A Wintergarde Gryphon In Wintergarde Keep Or The Carrion Fields.
    MustTargetWilhelm = 27,                                                             // What Are You Doing? Only Aim That Thing At Wilhelm!
    NotEnoughHealth = 28,                                                               // Not Enough Health!
    NoNearbyCorpses = 29,                                                               // There Are No Nearby Corpses To Use.
    TooManyGhouls = 30,                                                                 // You'Ve Created Enough Ghouls. Return To Gothik The Harvester At Death'S Breach.
    GoFurtherFromSunderedShard = 31,                                                    // Your Companion Does Not Want To Come Here.  Go Further From The Sundered Shard.
    MustBeInCatForm = 32,                                                               // Must Be In Cat Form
    MustBeDeathKnight = 33,                                                             // Only Death Knights May Enter Ebon Hold.
    MustBeInBearForm = 34,                                                              // Must Be In Bear Form
    MustBeNearHelplessVillager = 35,                                                    // You Must Be Within Range Of A Helpless Wintergarde Villager.
    CantTargetElementalMechanical = 36,                                                 // You Cannot Target An Elemental Or Mechanical Corpse.
    MustHaveUsedDalaranCrystal = 37,                                                    // This Teleport Crystal Cannot Be Used Until The Teleport Crystal In Dalaran Has Been Used At Least Once.
    YouAlreadyHoldSomething = 38,                                                       // You Are Already Holding Something In Your Hand. You Must Throw The Creature In Your Hand Before Picking Up Another.
    YouDontHoldAnything = 39,                                                           // You Don'T Have Anything To Throw! Find A Vargul And Use Gymer Grab To Pick One Up!
    MustBeCloseToValduran = 40,                                                         // Bouldercrag'S War Horn Can Only Be Used Within 10 Yards Of Valduran The Stormborn.
    NoPassenger = 41,                                                                   // You Are Not Carrying A Passenger. There Is Nobody To Drop Off.
    CantBuildMoreVehicles = 42,                                                         // You Cannot Build Any More Siege Vehicles.
    AlreadyCarryingCrusader = 43,                                                       // You Are Already Carrying A Captured Argent Crusader. You Must Return To The Argent Vanguard Infirmary And Drop Off Your Passenger Before You May Pick Up Another.
    CantDoWhileRooted = 44,                                                             // You Can'T Do That While Rooted.
    RequiresNearbyTarget = 45,                                                          // Requires A Nearby Target.
    NothingToDiscover = 46,                                                             // Nothing Left To Discover.
    NotEnoughTargets = 47,                                                              // No Targets Close Enough To Bluff.
    ConstructTooFar = 48,                                                               // Your Iron Rune Construct Is Out Of Range.
    RequiresGrandMasterEngineer = 49,                                                   // Requires Engineering (350)
    CantUseThatMount = 50,                                                              // You Can'T Use That Mount.
    NooneToEject = 51,                                                                  // There Is Nobody To Eject!
    TargetMustBeBound = 52,                                                             // The Target Must Be Bound To You.
    TargetMustBeUndead = 53,                                                            // Target Must Be Undead.
    TargetTooFar = 54,                                                                  // You Have No Target Or Your Target Is Too Far Away.
    MissingDarkMatter = 55,                                                             // Missing Reagents: Dark Matter
    CantUseThatItem = 56,                                                               // You Can'T Use That Item
    CantDoWhileCycyloned = 57,                                                          // You Can'T Do That While Cycloned
    TargetHasScroll = 58,                                                               // Target Is Already Affected By A Similar Effect
    PoisonTooStrong = 59,                                                               // That Anti-Venom Is Not Strong Enough To Dispel That Poison
    MustHaveLanceEquipped = 60,                                                         // You Must Have A Lance Equipped.
    MustBeCloseToMaiden = 61,                                                           // You Must Be Near The Maiden Of Winter'S Breath Lake.
    LearnedEverything = 62,                                                             // You Have Learned Everything From That Book
    PetIsDead = 63,                                                                     // Your Pet Is Dead
    NoValidTargets = 64,                                                                // There Are No Valid Targets Within Range.
    GmOnly = 65,                                                                        // Only Gms May Use That. Your Account Has Been Reported For Investigation.
    RequiresLevel58 = 66,                                                               // You Must Reach Level 58 To Use This Portal.
    AtHonorCap = 67,                                                                    // You Already Have The Maximum Amount Of Honor.
    HaveHotRod = 68,                                                                    // You Already Have A Hot Rod.
    PartygoerMoreBubbly = 69,                                                           // This Partygoer Wants Some More Bubbly.
    PartygoerNeedBucket = 70,                                                           // This Partygoer Needs A Bucket!
    PartygoerWantToDance = 71,                                                          // This Partygoer Wants To Dance With You.
    PartygoerWantFireworks = 72,                                                        // This Partygoer Wants To See Some Fireworks.
    PartygoerWantAppetizer = 73,                                                        // This Partygoer Wants Some More Hors D'Oeuvres.
    GoblinBatteryDepleted = 74,                                                         // The Goblin All-In-1-Der Belt'S Battery Is Depleted.
    MustHaveDemonicCircle = 75,                                                         // You Must Have A Demonic Circle Active.
    AtMaxRage = 76,                                                                     // You Already Have Maximum Rage
    Requires350Engineering = 77,                                                        // Requires Engineering (350)
    SoulBelongsToLichKing = 78,                                                         // Your Soul Belongs To The Lich King
    AttendantHasPony = 79,                                                              // Your Attendant Already Has An Argent Pony
    GoblinStartingMission = 80,                                                         // First, Overload The Defective Generator, Activate The Leaky Stove, And Drop A Cigar On The Flammable Bed.
    GasbotAlreadySent = 81,                                                             // You'Ve Already Sent In The Gasbot And Destroyed Headquarters!
    GoblinIsPartiedOut = 82,                                                            // This Goblin Is All Partied Out!
    MustHaveFireTotem = 83,                                                             // You Must Have A Magma, Flametongue, Or Fire Elemental Totem Active.
    CantTargetVampires = 84,                                                            // You May Not Bite Other Vampires.
    PetAlreadyAtYourLevel = 85,                                                         // Your Pet Is Already At Your Level.
    MissingItemRequiremens = 86,                                                        // You Do Not Meet The Level Requirements For This Item.
    TooManyAbominations = 87,                                                           // There Are Too Many Mutated Abominations.
    AllPotionsUsed = 88,                                                                // The Potions Have All Been Depleted By Professor Putricide.
    DefeatedEnoughAlready = 89,                                                         // You Have Already Defeated Enough Of Them.
    RequiresLevel65 = 90,                                                               // Requires Level 65
    DestroyedKtcOilPlatform = 91,                                                       // You Have Already Destroyed The Ktc Oil Platform.
    LaunchedEnoughCages = 92,                                                           // You Have Already Launched Enough Cages.
    RequiresBoosterRockets = 93,                                                        // Requires Single-Stage Booster Rockets. Return To Hobart Grapplehammer To Get More.
    EnoughWildCluckers = 94,                                                            // You Have Already Captured Enough Wild Cluckers.
    RequiresControlFireworks = 95,                                                      // Requires Remote Control Fireworks. Return To Hobart Grapplehammer To Get More.
    MaxNumberOfRecruits = 96,                                                           // You Already Have The Max Number Of Recruits.
    MaxNumberOfVolunteers = 97,                                                         // You Already Have The Max Number Of Volunteers.
    FrostmourneRenderedResurrect = 98,                                                  // Frostmourne Has Rendered You Unable To Resurrect.
    CantMountWithShapeshift = 99,                                                       // You Can'T Mount While Affected By That Shapeshift.
    FawnsAlreadyFollowing = 100,                                                        // Three Fawns Are Already Following You!
    AlreadyHaveRiverBoat = 101,                                                         // You Already Have A River Boat.
    NoActiveEnchantment = 102,                                                          // You Have No Active Enchantment To Unleash.
    EnoughHighbourneSouls = 103,                                                        // You Have Bound Enough Highborne Souls. Return To Arcanist Valdurian.
    Atleast40ydFromOilDrilling = 104,                                                   // You Must Be At Least 40 Yards Away From All Other Oil Drilling Rigs.
    AboveEnslavedPearlMiner = 106,                                                      // You Must Be Above The Enslaved Pearl Miner.
    MustTargetCorpseSpecial1 = 107,                                                     // You Must Target The Corpse Of A Seabrush Terrapin, Scourgut Remora, Or Spinescale Hammerhead.
    SlaghammerAlreadyPrisoner = 108,                                                    // Ambassador Slaghammer Is Already Your Prisoner.
    RequireAttunedLocation1 = 109,                                                      // Requires A Location That Is Attuned With The Naz'Jar Battlemaiden.
    NeedToFreeDrakeFirst = 110,                                                         // Free The Drake From The Net First!
    DragonmawAlliesAlreadyFollow = 111,                                                 // You Already Have Three Dragonmaw Allies Following You.
    RequireOpposableThumbs = 112,                                                       // Requires Opposable Thumbs.
    NotEnoughHealth2 = 113,                                                             // Not Enough Health
    EnoughForsakenTroopers = 114,                                                       // You Already Have Enough Forsaken Troopers.
    CannotJumpToBoulder = 115,                                                          // You Cannot Jump To Another Boulder Yet.
    SkillTooHigh = 116,                                                                 // Skill Too High.
    Already6SurvivorsRescued = 117,                                                     // You Have Already Rescued 6 Survivors.
    MustFaceShipsFromBalloon = 118,                                                     // You Need To Be Facing The Ships From The Rescue Balloon.
    CannotSuperviseMoreCultists = 119,                                                  // You Cannot Supervise More Than 5 Arrested Cultists At A Time.
    RequiresLevel85 = 120,                                                              // You Must Reach Level 85 To Use This Portal.
    MustBeBelow35Health = 121,                                                          // Your Target Must Be Below 35% Health.
    MustSelectSpecialization = 122,                                                     // You Must Select A Specialization First.
    TooWiseAndPowerful = 123,                                                           // You Are Too Wise And Powerful To Gain Any Benefit From That Item.
    TooCloseArgentLightwell = 124,                                                      // You Are Within 10 Yards Of Another Argent Lightwell.
    NotWhileShapeshifted = 125,                                                         // You Can'T Do That While Shapeshifted.
    ManaGemInBank = 126,                                                                // You Already Have A Mana Gem In Your Bank.
    FlameShockNotActive = 127,                                                          // You Must Have At Least One Flame Shock Active.
    CantTransform = 128,                                                                // You Cannot Transform Right Now
    PetMustBeAttacking = 129,                                                           // Your Pet Must Be Attacking A Target.
    GnomishEngineering = 130,                                                           // Requires Gnomish Engineering
    GoblinEngineering = 131,                                                            // Requires Goblin Engineering
    NoTarget = 132,                                                                     // You Have No Target.
    PetOutOfRange = 133,                                                                // Your Pet Is Out Of Range Of The Target.
    HoldingFlag = 134,                                                                  // You Can'T Do That While Holding The Flag.
    TargetHoldingFlag = 135,                                                            // You Can'T Do That To Targets Holding The Flag.
    PortalNotOpen = 136,                                                                // The Portal Is Not Yet Open.  Continue Helping The Druids At The Sanctuary Of Malorne.
    AggraAirTotem = 137,                                                                // You Need To Be Closer To Aggra'S Air Totem, In The West.
    AggraWaterTotem = 138,                                                              // You Need To Be Closer To Aggra'S Water Totem, In The North.
    AggraEarthTotem = 139,                                                              // You Need To Be Closer To Aggra'S Earth Totem, In The East.
    AggraFireTotem = 140,                                                               // You Need To Be Closer To Aggra'S Fire Totem, Near Thrall.
    FacingWrongWay = 141,                                                               // You Are Facing The Wrong Way.
    TooCloseToMakeshiftDynamite = 142,                                                  // You Are Within 10 Yards Of Another Makeshift Dynamite.
    NotNearSapphireSunkenShip = 143,                                                    // You Must Be Near The Sunken Ship At Sapphire'S End In The Jade Forest.
    DemonsHealthFull = 144,                                                             // That Demon'S Health Is Already Full.
    OnyxSerpentNotOverhead = 145,                                                       // Wait Until The Onyx Serpent Is Directly Overhead.
    ObjectiveAlreadyComplete = 146,                                                     // Your Objective Is Already Complete.
    PushSadPandaTowardsTown = 147,                                                      // You Can Only Push Sad Panda Towards Sad Panda Town!
    TargetHasStartdust2 = 148,                                                          // Target Is Already Affected By Stardust No. 2.
    ElementiumGemClusters = 149,                                                        // You Cannot Deconstruct Elementium Gem Clusters While Collecting Them!
    YouDontHaveEnoughHealth = 150,                                                      // You Don'T Have Enough Health.
    YouCannotUseTheGatewayYet = 151,                                                    // You Cannot Use The Gateway Yet.
    ChooseSpecForAscendance = 152,                                                      // You Must Choose A Specialization To Use Ascendance.
    InsufficientBloodCharges = 153,                                                     // You Have Insufficient Blood Charges.
    NoFullyDepletedRunes = 154,                                                         // No Fully Depleted Runes.
    NoMoreCharges = 155,                                                                // No More Charges.
    StatueIsOutOfRangeOfTarget = 156,                                                   // Statue Is Out Of Range Of The Target.
    YouDontHaveAStatueSummoned = 157,                                                   // You Don'T Have A Statue Summoned.
    YouHaveNoSpiritActive = 158,                                                        // You Have No Spirit Active.
    BothDisesasesMustBeOnTarget = 159,                                                  // Both Frost Fever And Blood Plague Must Be Present On The Target.
    CantDoThatWithOrbOfPower = 160,                                                     // You Can'T Do That While Holding An Orb Of Power.
    CantDoThatWhileJumpingOrFalling = 161,                                              // You Can'T Do That While Jumping Or Falling.
    MustBeTransformedByPolyformicAcid = 162,                                            // You Must Be Transformed By Polyformic Acid.
    NotEnoughAcidToStoreTransformation = 163,                                           // There Isn'T Enough Acid Left To Store This Transformation.
    MustHaveFlightMastersLicense = 164,                                                 // You Must Obtain A Flight Master'S License Before Using This Spell.
    AlreadySampledSapFromFeeder = 165,                                                  // You Have Already Sampled Sap From This Feeder.
    MustBeNewrMantidFeeder = 166,                                                       // Requires You To Be Near A Mantid Feeder In The Heart Of Fear.
    TargetMustBeInDirectlyFront = 167,                                                  // Target Must Be Directly In Front Of You.
    CantDoThatWhileMythicKeystoneIsActive = 168,                                        // You Can'T Do That While A Mythic Keystone Is Active.
    WrongClassForMount = 169,                                                           // You Are Not The Correct Class For That Mount.
    NothingLeftToDiscover = 170,                                                        // Nothing Left To Discover.
    NoExplosivesAvailable = 171,                                                        // There Are No Explosives Available.
    YouMustBeFlaggedForPvp = 172,                                                       // You Must Be Flagged For Pvp.
    RequiresBattleRations = 173,                                                        // Requires Battle Rations Or Meaty Haunch
    RequiresBrittleRoot = 174,                                                          // Requires Brittle Root
    RequiresLaborersTool = 175,                                                         // Requires Laborer'S Tool
    RequiresUnexplodedCannonball = 176,                                                 // Requires Unexploded Cannonball
    RequiresMisplacedKeg = 177,                                                         // Requires Misplaced Keg
    RequiresLiquidFire = 178,                                                           // Requires Liquid Fire, Jungle Hops, Or Spirit-Kissed Water
    RequiresKrasariIron = 179,                                                          // Requires Krasari Iron
    RequiresSpiritKissedWater = 180,                                                    // Requires Spirit-Kissed Water
    RequiresSnakeOil = 181,                                                             // Requires Snake Oil
    ScenarioIsInProgress = 182,                                                         // You Can'T Do That While A Scenario Is In Progress.
    RequiresDarkmoonFaireOpen = 183,                                                    // Requires The Darkmoon Faire To Be Open.
    AlreadyAtValorCap = 184,                                                            // Already At Valor Cap
    AlreadyCommendedByThisFaction = 185,                                                // Already Commended By This Faction
    OutOfCoins = 186,                                                                   // Out Of Coins! Pickpocket Humanoids To Get More.
    OnlyOneElementalSpirit = 187,                                                       // Only One Elemental Spirit On A Target At A Time.
    DontKnowHowToTameDirehorns = 188,                                                   // You Do Not Know How To Tame Direhorns.
    MustBeNearBloodiedCourtGate = 189,                                                  // You Must Be Near The Bloodied Court Gate.
    YouAreNotElectrified = 190,                                                         // You Are Not Electrified.
    ThereIsNothingToBeFetched = 191,                                                    // There Is Nothing To Be Fetched.
    RequiresTheThunderForge = 192,                                                      // Requires The Thunder Forge.
    CannotUseTheDiceAgainYet = 193,                                                     // You Cannot Use The Dice Again Yet.
    AlreadyMemberOfBrawlersGuild = 194,                                                 // You Are Already A Member Of The Brawler'S Guild.
    CantChangeSpecInCelestialChallenge = 195,                                           // You May Not Change Talent Specializations During A Celestial Challenge.
    SpecDoesMatchChallenge = 196,                                                       // Your Talent Specialization Does Not Match The Selected Challenge.
    YouDontHaveEnoughCurrency = 197,                                                    // You Don'T Have Enough Currency To Do That.
    TargetCannotBenefitFromSpell = 198,                                                 // Target Cannot Benefit From That Spell
    YouCanOnlyHaveOneHealingRain = 199,                                                 // You Can Only Have One Healing Rain Active At A Time.
    TheDoorIsLocked = 200,                                                              // The Door Is Locked.
    YouNeedToSelectWaitingCustomer = 201,                                               // You Need To Select A Customer Who Is Waiting In Line First.
    CantChangeSpecDuringTrial = 202,                                                    // You May Not Change Specialization While A Trial Is In Progress.
    CustomerNeedToGetInLine = 203,                                                      // You Must Wait For Customers To Get In Line Before You Can Select Them To Be Seated.
    MustBeCloserToGazloweObjective = 204,                                               // Must Be Closer To One Of Gazlowe'S Objectives To Deploy!
    MustBeCloserToThaelinObjective = 205,                                               // Must Be Closer To One Of Thaelin'S Objectives To Deploy!
    YourPackOfVolenIsFull = 206,                                                        // Your Pack Of Volen Is Already Full!
    Requires600MiningOrBlacksmithing = 207,                                             // Requires 600 Mining Or Blacksmithing
    ArkoniteProtectorNotInRange = 208,                                                  // The Arkonite Protector Is Not In Range.
    TargetCannotHaveBothBeacons = 209,                                                  // You Are Unable To Have Both Beacon Of Light And Beacon Of Faith On The Same Target.
    CanOnlyUseOnAfkPlayer = 210,                                                        // Can Only Be Used On Afk Players.
    NoLootableCorpsesInRange = 211,                                                     // No Lootable Corpse In Range
    ChimaeronTooCalmToTame = 212,                                                       // Chimaeron Is Too Calm To Tame Right Now.
    CanOnlyCarryOneTypeOfMunitions = 213,                                               // You May Only Carry One Type Of Blackrock Munitions.
    OutOfBlackrockMunitions = 214,                                                      // You Have Run Out Of Blackrock Munitions.
    CarryingMaxAmountOfMunitions = 215,                                                 // You Are Carrying The Maximum Amount Of Blackrock Munitions.
    TargetIsTooFarAway = 216,                                                           // Target Is Too Far Away.
    CannotUseDuringBossEncounter = 217,                                                 // Cannot Use During A Boss Encounter.
    MustHaveMeleeWeaponInBothHands = 218,                                               // Must Have A Melee Weapon Equipped In Both Hands
    YourWeaponHasOverheated = 219,                                                      // Your Weapon Has Overheated.
    MustBePartyLeaderToQueue = 220,                                                     // You Must Be A Party Leader To Queue Your Group.
    NotEnoughFuel = 221,                                                                // Not Enough Fuel
    YouAreAlreadyDisguised = 222,                                                       // You Are Already Disguised!
    YouNeedToBeInShredder = 223,                                                        // You Need To Be In A Shredder To Chop This Up!
    FoodCannotEatFood = 224,                                                            // Food Cannot Eat Food
    MysteriousForcePreventsOpeningChest = 225,                                          // A Mysterious Force Prevents You From Opening The Chest.
    CantDoThatWhileHoldingEmpoweredOre = 226,                                           // You Can'T Do That While Holding Empowered Ore.
    NotEnoughAmmunition = 227,                                                          // Not Enough Ammunition!
    YouNeedBeatfaceTheGladiator = 228,                                                  // You Need Beatface The Sparring Arena Gladiator To Break This!
    YouCanOnlyHaveOneWaygate = 229,                                                     // You Can Only Have One Waygate Open. Disable An Activated Waygate First.
    YouCanOnlyHaveTwoWaygates = 230,                                                    // You Can Only Have Two Waygates Open. Disable An Activated Waygate First.
    YouCanOnlyHaveThreeWaygates = 231,                                                  // You Can Only Have Three Waygates Open. Disable An Activated Waygate First.
    RequiresMageTower = 232,                                                            // Requires Mage Tower
    RequiresSpiritLodge = 233,                                                          // Requires Spirit Lodge
    FrostWyrmAlreadyActive = 234,                                                       // A Frost Wyrm Is Already Active.
    NotEnoughRunicPower = 235,                                                          // Not Enough Runic Power
    YouAreThePartyLeader = 236,                                                         // You Are The Party Leader.
    YulonIsAlreadyActive = 237,                                                         // Yu'Lon Is Already Active.
    AStampedeIsAlreadyActive = 238,                                                     // A Stampede Is Already Active.
    YouAreAlreadyWellFed = 239,                                                         // You Are Already Well Fed.
    CantDoThatUnderSuppressiveFire = 240,                                               // You Cannot Do That While Under Suppressive Fire.
    YouAlreadyHaveMurlocSlop = 241,                                                     // You Already Have A Piece Of Murloc Slop.
    YouDontHaveArtifactFragments = 242,                                                 // You Don'T Have Any Artifact Fragments.
    YouArentInAParty = 243,                                                             // You Aren'T In A Party.
    Requires20Ammunition = 244,                                                         // Requires 30 Ammunition!
    Requires30Ammunition = 245,                                                         // Requires 20 Ammunition!
    YouAlreadyHaveMaxOutcastFollowers = 246,                                            // You Already Have The Maximum Amount Of Outcasts Following You.
    NotInWorldPvpZone = 247,                                                            // Not In World Pvp Zone.
    AlreadyAtResourceCap = 248,                                                         // Already At Resource Cap
    ApexisSentinelRequiresEnergy = 249,                                                 // This Apexis Sentinel Requires Energy From A Nearby Apexis Pylon To Be Powered Up.
    YouMustHave3OrFewerPlayer = 250,                                                    // You Must Have 3 Or Fewer Players.
    YouAlreadyReadTreasureMap = 251,                                                    // You Have Already Read That Treasure Map.
    MayOnlyUseWhileGarrisonUnderAttack = 252,                                           // You May Only Use This Item While Your Garrison Is Under Attack.
    RequiresActiveMushrooms = 253,                                                      // This Spell Requires Active Mushrooms For You To Detonate.
    RequiresFasterTimeWithRacer = 254,                                                  // Requires A Faster Time With The Basic Racer
    RequiresInfernoShotAmmo = 255,                                                      // Requires Inferno Shot Ammo!
    YouCannotDoThatRightNow = 256,                                                      // You Cannot Do That Right Now.
    ATrapIsAlreadyPlacedThere = 257,                                                    // A Trap Is Already Placed There.
    YouAreAlreadyOnThatQuest = 258,                                                     // You Are Already On That Quest.
    RequiresFelforgedCudgel = 259,                                                      // Requires A Felforged Cudgel!
    CantTakeWhileBeingDamaged = 260,                                                    // Can'T Take While Being Damaged!
    YouAreBoundToDraenor = 261,                                                         // You Are Bound To Draenor By Archimonde'S Magic.
    AlreayHaveMaxNumberOfShips = 262,                                                   // You Already Have The Maximum Number Of Ships Your Shipyard Can Support.
    MustBeAtShipyard = 263,                                                             // You Must Be At Your Shipyard.
    RequiresLevel3MageTower = 264,                                                      // Requires A Level 3 Mage Tower.
    RequiresLevel3SpiritLodge = 265,                                                    // Requires A Level 3 Spirit Lodge.
    YouDoNotLikeFelEggsAndHam = 266,                                                    // You Do Not Like Fel Eggs And Ham.
    AlreadyEnteredInThisAgreement = 267,                                                // You Have Already Entered In To This Trade Agreement.
    CannotStealThatWhileGuardsAreOnDuty = 268,                                          // You Cannot Steal That While Guards Are On Duty.
    YouAlreadyUsedVantusRune = 269,                                                     // You Have Already Used A Vantus Rune This Week.
    ThatItemCannotBeObliterated = 270,                                                  // That Item Cannot Be Obliterated.
    NoSkinnableCorpseInRange = 271,                                                     // No Skinnable Corpse In Range
    MustBeMercenaryToUseTrinket = 272,                                                  // You Must Be A Mercenary To Use This Trinket.
    YouMustBeInCombat = 273,                                                            // You Must Be In Combat.
    NoEnemiesNearTarget = 274,                                                          // No Enemies Near Target.
    RequiresLeyspineMissile = 275,                                                      // Requires A Leyspine Missile
    RequiresBothCurrentsConnected = 276,                                                // Requires Both Currents Connected.
    CantDoThatInDemonForm = 277,                                                        // Can'T Do That While In Demon Form (Yet)
    YouDontKnowHowToTameMechs = 278,                                                    // You Do Not Know How To Tame Or Obtain Lore About Mechs.
    CannotCharmAnyMoreWithered = 279,                                                   // You Cannot Charm Any More Withered.
    RequiresActiveHealingRain = 280,                                                    // Requires An Active Healing Rain.
    AlreadyCollectedAppearances = 281,                                                  // You'Ve Already Collected These Appearances
    CannotResurrectSurrenderedToMadness = 282,                                          // Cannot Resurrect Someone Who Has Surrendered To Madness
    YouMustBeInCatForm = 283,                                                           // You Must Be In Cat Form.
    YouCannotReleaseSpiritYet = 284,                                                    // You Cannot Release Spirit Yet.
    NoFishingNodesNearby = 285,                                                         // No Fishing Nodes Nearby.
    YouAreNotInCorrectSpec = 286,                                                       // You Are Not The Correct Specialization.
    UlthaleshHasNoPowerWithoutSouls = 287,                                              // Ulthalesh Has No Power Without Souls.
    CannotCastThatWithVoodooTotem = 288,                                                // You Cannot Cast That While Talented Into Voodoo Totem.
    AlreadyCollectedThisAppearance = 289,                                               // You'Ve Already Collected This Appearance.
    YourPetMaximumIsAlreadyHigh = 290,                                                  // Your Total Pet Maximum Is Already This High.
    YouDontHaveEnoughWithered = 291,                                                    // You Do Not Have Enough Withered To Do That.
    RequiresNearbySoulFragment = 292,                                                   // Requires A Nearby Soul Fragment.
    RequiresAtLeast10Withered = 293,                                                    // Requires At Least 10 Living Withered
    RequiresAtLeast14Withered = 294,                                                    // Requires At Least 14 Living Withered
    RequiresAtLeast18Withered = 295,                                                    // Requires At Least 18 Living Withered
    Requires2WitheredManaRagers = 296,                                                  // Requires 2 Withered Mana-Ragers
    Requires1WitheredBerserke = 297,                                                    // Requires 1 Withered Berserker
    Requires2WitheredBerserker = 298,                                                   // Requires 2 Withered Berserkers
    TargetHealthIsTooLow = 299,                                                         // Target'S Health Is Too Low
    CannotShapeshiftWhileRidingStormtalon = 300,                                        // You Cannot Shapeshift While Riding Stormtalon
    CannotChangeSpecInCombatTraining = 301,                                             // You Can Not Change Specializations While In Combat Training.
    UnknownPhenomenonPreventsLeylineConnection = 302,                                   // Unknown Phenomenon Is Preventing A Connection To The Leyline.
    TheNightmareObscuresYourVision = 303,                                               // The Nightmare Obscures Your Vision.
    YouAreInWrongClassSpec = 304,                                                       // You Are In The Wrong Class Specialization.
    ThereAreNoValidCorpsesNearby = 305,                                                 // There Are No Valid Corpses Nearby.
    CantCastThatRightNow = 306,                                                         // Can'T Cast That Right Now.
    NotEnoughAncientMan = 307,                                                          // Not Enough Ancient Mana.
    RequiresSongScroll = 308,                                                           // Requires A Song Scroll To Function.
    MustHaveArtifactEquipped = 309,                                                     // You Must Have An Artifact Weapon Equipped.
    RequiresCatForm = 310,                                                              // Requires Cat Form.
    RequiresBearForm = 311,                                                             // Requires Bear Form.
    RequiresConjuredFood = 312,                                                         // Requires Either A Conjured Mana Pudding Or Conjured Mana Fritter.
    RequiresArtifactWeapon = 313,                                                       // Requires An Artifact Weapon.
    YouCantCastThatHere = 314,                                                          // You Can'T Cast That Here
    CantDoThatOnClassTrial = 315,                                                       // You Cannot Do That While On A Class Trial.
    RitualOfDoomOncePerDay = 316,                                                       // You Can Only Benefit From The Ritual Of Doom Once Per Day.
    CannotRitualOfDoomWhileSummoningSiters = 317,                                       // You Cannot Perform The Ritual Of Doom While Attempting To Summon The Sisters.
    LearnedAllThatYouCanAboutYourArtifact = 318,                                        // You Have Learned All That You Can About Your Artifact.
    CantCallPetWithLoneWolf = 319,                                                      // You Cannot Use Call Pet While Lone Wolf Is Active.
    TargetCannotAlreadyHaveOrbOfPower = 320,                                            // Target cannot already have a Orb of Power.
    YouMustBeInAnInnToStrumThatGuitar = 321,                                            // You must be in an inn to strum that guitar.
    YouCannotReachTheLatch = 322,                                                       // You cannot reach the latch.
    RequiresABrimmingKeystone = 323,                                                    // Requires A Brimming Keystone.
    YouMustBeWieldingTheUnderlightAngler = 324,                                         // You Must Be Wielding The Underlight Angler.
    YourTargetMustBeShackled = 325,                                                     // Your Target Must Be Shackled.
    YouAlreadyPossesAllOfTheKnowledgeContainedInThosePages = 326,                       // You Already Possess All Of The Knowledge Contained In These Pages.
    YouCantRiskGettingTheGrummelsWet = 327,                                             // You Can'T Risk Getting The Grummels Wet!
    YouCannotChangeSpecializationRightNow = 328,                                        // You Cannot Change Specializations Right Now.
    YouveReachedTheMaximumNumberOfArtifactResearchNotesAvailable = 329,                 // You'Ve Reached The Maximum Number Of Artifact Research Notes Available.
    YouDontHaveEnoughNethershards = 330,                                                // You Don'T Have Enough Nethershards.
    TheSentinaxIsNotPatrollingThisArea = 331,                                           // The Sentinax Is Not Patrolling This Area.
    TheSentinaxCannotOpenAnotherPortalRightNow = 332,                                   // The Sentinax Cannot Open Another Portal Right Now.
    YouCannotGainAdditionalReputationWithThisItem = 333,                                // You Cannot Gain Additional Reputation With This Item.
    CantDoThatWhileGhostWolfForm = 334,                                                 // Can'T Do That While In Ghost Wolf Form.
    YourSuppliesAreFrozen = 335,                                                        // Your Supplies Are Frozen.
    YouDoNotKnowHowToTameFeathermanes = 336,                                            // You Do Not Know How To Tame Feathermanes.
    YouMustReachArtifactKnowledgeLevel25 = 337,                                         // You Must Reach Artifact Knowledge Level 25 To Use The Tome.
    RequiresANetherPortalDisruptor = 338,                                               // Requires A Nether Portal Disruptor.
    YouAreNotTheCorrectRankToUseThisItem = 339,                                         // You Are Not The Correct Rank To Use This Item.
    MustBeStandingNearInjuredChromieInMountHyjal = 340,                                 // Must Be Standing Near The Injured Chromie In Mount Hyjal.
    TheresNothingFurtherYouCanLearn = 341,                                              // There'S Nothing Further You Can Learn.
    RemoveCannonsHeavyIronPlatingFirst = 342,                                           // You Should Remove The Cannon'S Heavy Iron Plating First.
    RemoveCannonsElectrokineticDefenseGridFirst = 343,                                  // You Should Remove The Cannon'S Electrokinetic Defense Grid First.
    RequiresTheArmoryKeyAndDendriteClusters = 344,                                      // You Are Missing Pieces Of The Armory Key Or Do Not Have Enough Dendrite Clusters.
    ThisItemRequiresBasicObliterumToUpgrade = 345,                                      // This Item Requires Basic Obliterum To Upgrade.
    ThisItemRequiresPrimalObliterumToUpgrade = 346,                                     // This Item Requires Primal Obliterum To Upgrade.
    ThisItemRequiresFlightMastersWhistle = 347,                                         // This Item Requires A Flight Master'S Whistle.
    RequiresMorrisonsMasterKey = 348,                                                   // Requires Morrison'S Master Key.
    RequiresPowerThatEchoesThatOfTheAugari = 349,                                       // Will Only Open To One Wielding The Power That Echoes That Of The Augari.
    ThatPlayerHasAPendingTotemicRevival = 350,                                          // That Player Has A Pending Totemic Revival.
    YouHaveNoFireMinesDeployed = 351,                                                   // You Have No Fire Mines Deployed.
    MustBeAffectedBySpiritPowder = 352,                                                 // You Must Be Affected By The Spirit Powder To Take The Phylactery.
    YouAreBlockedByAStructureAboveYou = 353,                                            // You Are Blocked By A Structure Above You.
    Requires100ImpMeat = 354,                                                           // Requires 100 Imp Meat.
    YouHaveNotObtainedAnyBackgroundFilters = 355,                                       // You Have Not Obtained Any Background Filters.
    NothingInterestingPostedHereRightNow = 356,                                         // There Is Nothing Interesting Posted Here Right Now.
    ParagonReputationRequiresHigherLevel = 357,                                         // Paragon Reputation Is Not Available Until A Higher Level.
    UunaIsMissing = 358,                                                                // Uuna Is Missing.
    OnlyOtherHivemindMembersMayJoin = 359,                                              // Only Other Members Of Their Hivemind May Join With Them.
    NoValidFlaskPresent = 360,                                                          // No Valid Flask Present.
    NoWildImpsToSacrifice = 361,                                                        // There Are No Wild Imps To Sacrifice.
    YouAreCarryingTooMuchIron = 362,                                                    // You Are Carrying Too Much Iron
    YouHaveNoIronToCollect = 363,                                                       // You Have No Iron To Collect
    YouHaveNoWildImps = 364,                                                            // You Have No Available Wild Imps.
    NeedsRepairs = 365,                                                                 // Needs Repairs.
    YouAreCarryingTooMuchWood = 366,                                                    // You'Re Carrying Too Much Wood.
    YouAreAlreadyCarryingRepairParts = 367,                                             // You'Re Already Carrying Repair Parts.
    YouHaveNotUnlockedFlightWhistleForZone = 368,                                       // You Have Not Unlocked The Flight Whistle For This Zone.
    ThereAreNoUnlockedFlightPointsNearby = 369,                                         // There Are No Unlocked Flight Points Nearby To Take You To.
    YouMustHaveAFelguard = 370,                                                         // You Must Have A Felguard.
    TargetHasNoFesteringWounds = 371,                                                   // The Target Has No Festering Wounds.
    YouDontHaveDeadlyOrWoundPoisonActive = 372,                                         // You Do Not Have Deadly Poison Or Wound Poison Active.
    CannotReadSoldierDogTagWithoutHeadlampOn = 373,                                     // You Cannot Read The Soldier'S Dog Tag Without Your Headlamp On.
    YouHaveNoWoodToCollect = 374,                                                       // You Have No Wood To Collect.
    YouAreNotWearingAShirt = 375,                                                       // You Are Not Wearing A Shirt!
    TargetMustBeDead = 376,                                                             // Target Must Be Dead.
    YourTargetIsAlreadyEmbiggified = 377,                                               // Your Target Is Already Embiggified.
    YouMustTargetASinisterGladiatorItem = 378,                                          // You Must Target A Sinister Gladiator'S Item To Upgrade.
    ThisItemLevelIsTooHighForThisUpgrade = 379,                                         // This Item'S Level Is Too High For This Upgrade.
    TheBallistaCannotBeUsedWhileOnFire = 380,                                           // The Ballista Cannot Be Used While On Fire.
    YouMustTargetADreadGladiatorItem = 381,                                             // You Must Target A Dread Gladiator'S Item To Upgrade.
    YouDoKnotKnowHowToTameBloodBeasts = 382,                                            // You Do Not Know How To Tame Blood Beasts.
    CanOnlyBeUsedInTheEvening = 385,                                                    // Can Only Be Used In The Evening.
    RequiresPakuToBeYourChosenLoa = 386,                                                // Requires Pa'Ku To Be Your Chosen Loa.
    RequiresVigorEngaged = 387,                                                         // Requires V.I.G.O.R. Engaged.
    YourTargetIsNotHungry = 388,                                                        // Your Target Is Not Hungry.
    YouCanOnlyHaveOnTreasureMapMission = 389,                                           // You Can Only Have One Treasure Map Mission At A Time.
    YouAlreadyHaveASilasSphereOfTransmutation = 390,                                    // You Already Have A Silas' Sphere Of Transmuation.
    YouDoNotHaveTheMalletOfThunderousSkins = 391,                                       // You Do Not Have The Mallet Of Thunderous Skins.
    YouMustHaveAnOpenStableSlot = 393,                                                  // You Must Have An Open Stable Slot.
    DoesNotWorkOnCritters = 394,                                                        // Does Not Work On Critters.
    CanOnlyBeUsedOnHati = 395,                                                          // Can Only Be Used On Hati.
    YouAlreadyHaveIwensEnchantingRod = 396,                                             // You Already Have An Iwen'S Enchanting Rod.
    YouAlreadyHaveMalletOfThunderousSkins = 397,                                        // You Already Have A Mallet Of Thunderous Skins.
    CanOnlyBeUsedOnInertTideWatchersOrVoodooMasks = 398,                                // Can Only Be Used On Inert Tide Watchers Or Inert Voodoo Masks.
    YouMustBeAtShrineToMakeOfferingToLoa = 399,                                         // You Must Be At A Shrine To Make An Offering To A Loa.
    RequiresEmeraldEmpowerment = 400,                                                   // Requires Emerald Empowerment.
    YouMustBeAnHonoredTauren = 401,                                                     // You Must Be An Honored Tauren.
    RequiresChitterspineMeat = 402,                                                     // Requires Chitterspine Meat.
    RequiresHeartForge = 403,                                                           // Requires Heart Forge.
    NotAuthorizedToAccessChargingStation = 405,                                         // You Are Not Authorized To Access This Charging Station. Speak To Flux.
    RequiresMardivasArcaneCoffer = 406,                                                 // Requires Mardivas'S Arcane Coffer
    RequiresHeartOfAzerothAtopHeartForge = 407,                                         // Requires Heart Of Azeroth Placed Atop Heart Forge.
    RequiresBrinestonePickaxe = 408,                                                    // Requires A Brinestone Pickaxe.
    YouAlreadyCollectedDataOnThisTarget = 409,                                          // You Have Already Collected Data On This Target.
    YouAlreadyHaveThisEssenceForCurrentSpec = 410,                                      // You Already Have This Essence For Your Current Loot Specialization
    YouCannotSummonAnotherPetWhileRidingHati = 411,                                     // You Cannot Summon Another Pet While Riding Hati.
    YouHaveAlreadyCollectedThisAzerothMini = 422,                                       // You Have Already Collected This Azeroth Mini
    YourTargetIsAlreadyAffectedByTeaTime = 412,                                         // Your Target Is Already Affected By Tea Time!
    YouMustCompleteQuestTheHeartForgeToInfuseEssence = 413,                             // You Must Complete The Quest "The Heart Forge" To Infuse An Essence
    ThisTargetDoesNotHaveYourRazorCoral = 414,                                          // This Target Does Not Have Your Razor Coral.
    YouDoNotHaveEnoughOfThatItem = 415,                                                 // You Do Not Have Enough Of That Item.
    YourTargetIsNotWearingUnboundCursedLoversRing = 417,                                // Your Target Is Not Wearing An Unbound Cursed Lover'S Ring
    YourCursedLoversRingIsAlredyBound = 418,                                            // Your Cursed Lover'S Ring Is Already Bound
    YouMustTargetANotoriusGladiatorItem = 421,                                          // You Must Target A Notorious Gladiator'S Item To Upgrade.
    YouCantCarryMorePickaxesChumSeeds = 423,                                            // You Can'T Carry Any More Brinestone Pickaxes, Chum, Or Germinating Seeds.
    RequiresHolidayFeastOfWinterWeil = 424,                                             // Requires Holiday: Feast Of Winter Veil
    RequiresAshjrakamasShroudOfResolve = 425,                                           // Requires Ashjra'Kamas, Shroud Of Resolve.
    RequiresWarMode = 426,                                                              // Requires War Mode.
    OnlyOneOfThisMaskMayBeWorn = 427,                                                   // Only One Of This Mask May Be Worn.
    YouCannotAscendWhileTheTarragrueIsNearby = 428,                                     // You Cannot Ascend While The Tarragrue Is Nearby.
    TargetDoesNotHaveAValidAzeriteEssence = 429,                                        // Target Does Not Have A Valid Azerite Essence.
    YourMindIsStillRecoveringFromRecentVision = 430,                                    // Your Mind Is Still Recovering From A Recent Vision.
    RequiresVesselOfHorrificVisions = 431,                                              // Requires Vessel Of Horrific Visions.
    RequiresAllPartyMembersToBeWearingAshjrakamasShroudOfResolve = 432,                 // Requires All Party Members To Be Wearing Ashjra'Kamas, Shroud Of Resolve.
    RequiresAllPartyMembersToPossessAVesselOfHorrificVisions = 434,                     // Requires All Party Members To Possess A Vessel Of Horrific Visions.
    YouAlreadyHaveTheHighestRankedEssenceAvailableFromThisSource = 435,                 // You Already Have The Highest Ranked Essence Available From This Source.
    RequiresDarkmoonGameToken = 436,                                                    // Requires Darkmoon Game Token.
    YouAreNotTheRightProfession = 437,                                                  // You Are Not The Right Profession.
    YouAlreadyKnowHowToCraftAVoidFocus = 438,                                           // You Already Know How To Craft A Void Focus.
    YouAlreadyKnowTheRecipesInThisBook = 439,                                           // You Already Know The Recipes In This Book.
    YouMustTargetACorruptedGladiatorsItem = 440,                                        // You Must Target A Corrupted Gladiator'S Item To Upgrade.
    RequiresTheFixItStick = 441,                                                        // Requires The Fix-It-Stick.
    ThatItemCannotReceiveAdditionalSockets = 442,                                       // That Item Cannot Receive Additional Sockets.
    YouAlreadyHaveAContractedVeteranTroop = 443,                                        // You Already Have A Contracted Veteran Troop.
    YouAreCurrentlyAtYourTroopCapacity = 444,                                           // You Are Currently At Your Troop Capacity.
    YouDontHaveEnoughAnima = 445,                                                       // You Don'T Have Enough Anima
    TargetAlreadyHoldingVoidTouchedSkull = 446,                                         // That Player Is Already Holding A Void-Touched Skull.
    TargetsInventoryIsFull = 447,                                                       // Target'S Inventory Is Full.
    TargetsMindIsProtectedByNeuralSilencer = 448,                                       // Your Target'S Mind Is Protected By A Neural Silencer.
    AllTargetsMindsAreProtectedByNeuralSilencers = 449,                                 // All Of Your Targets' Minds Are Protected By Neural Silencers.
    YouMustFindAMorePowerfulCoreToProgressYourCloakRanksFurther = 450,                  // You Must Find A More Powerful Core To Progress Your Cloak Ranks Further.
    YouCannotUseThisItemInWarMode = 451,                                                // You Cannot Use This Item In War Mode.
    YouCannotMakeYourCampHere = 452,                                                    // You Cannot Make Your Camp Here.
    RequiresTitanicBeacon = 453,                                                        // Requires Titanic Beacon
    ThatObjectIsLocked = 454,                                                           // That Object Is Locked.
    InvalidCombination = 455,                                                           // Invalid Combination.
    NoNearbyEnemyPlayersAreCorrupted = 456,                                             // No Nearby Enemy Players Are Corrupted.
    ThatSpellIsAlreadyActive = 457,                                                     // That Spell Is Already Active
    YouCannotUseThisWhenTheTarragrueHasBeenAlerted = 458,                               // You Cannot Use This When The Tarragrue Has Been Alerted.
    ThatGuestAlreadyHasTea = 459,                                                       // That Guest Already Has Tea.
    RequiresShadowlandsSkinning = 460,                                                  // Requires Shadowlands Skinning.
    RequiresHuntersMarkOnATarget = 461,                                                 // Requires Hunter'S Mark On A Target.
    HoundmasterLokseyIsBusy = 462,                                                      // Houndmaster Loksey Is Busy.
    RequiresCoilOfRope = 463,                                                           // Requires Coil Of Rope.
    MustBeInARestArea = 464,                                                            // Must Be In A Rest Area.
    TargetIsLinkedToSomebodyElse = 465,                                                 // Target Is Linked To Somebody Else.
    YouDontHaveASummonedGhoul = 466,                                                    // You Don'T Have A Summoned Ghoul.
    OneOfYourPartyMembersIsAnIneligibleClass = 467,                                     // One Of Your Party Members Is An Ineligible Class.
    YouMustSelectASoulbindBossAndTierFirst = 468,                                       // You Must Select A Soulbind, Boss, And Tier First.
    ThatGuestDoesntWantThis = 469,                                                      // That Guest Doesn'T Want This.
    YouMustDefeatTheEmpoweredGuardToAscend = 470,                                       // You Must Defeat The Empowered Guard To Ascend.
    RequiresSoulsteelForge = 471,                                                       // Requires Soulsteel Forge.
    RequiresProofOfPurity = 472,                                                        // Requires Proof Of Purity
    RequiresProofOfHumility = 473,                                                      // Requires Proof Of Humility
    RequiresProofOfCourage = 474,                                                       // Requires Proof Of Courage
    RequiresProofOfWisdom = 475,                                                        // Requires Proof Of Wisdom
    RequiresProofOfLoyalty = 476,                                                       // Requires Proof Of Loyalty
    RequiresArcaneSpecilization = 477,                                                  // Requires Arcane Specilization.
    PleaseGatherYourPartyBeforeQueuing = 478,                                           // Please Gather Your Party Before Queuing.
    YouDoNotKnowHowToTameGargon = 479,                                                  // You Do Not Know How To Tame Gargon.
    RequiresDeadSpriggan = 480,                                                         // Requires Dead Spriggan
    YouAlreadyUsedAProfessionJournalThisWeek = 481,                                     // You Have Already Used A Profession Journal This Week.
    RequiresMordretharTheDeathGate = 482,                                               // Requires Mord'Rethar: The Death Gate.
    RequiresPlaguefallen = 483,                                                         // Requires Plaguefallen
    YouCannotFitThroughThere = 484,                                                     // You Cannot Fit Through There.
    ABindingRitualPreventsThisFromOpening = 485,                                        // A Binding Ritual Prevents This From Opening.
    ThatCharmIsAlreadyApplied = 486,                                                    // That Charm Is Already Applied.
    ThatSigilIsAlreadyApplied = 487,                                                    // That Sigil Is Already Applied.
    AtLeastOneGuestMustRsvpBeforeYouOpenCourt = 488,                                    // At Least One Guest Must Rsvp Before You Open Court.
    ThereIsNoTimeLimitToIncrease = 489,                                                 // There Is No Time Limit To Increase.
    YourHeartOfAzerothIsCurrentlyDisabled = 490,                                        // Your Heart Of Azeroth Is Currently Disabled.
    EssenceYouAreTryingToActivateIsInvalid = 491,                                       // The Essence You Are Trying To Activate Is Invalid.
    RequiresMedallionOfService = 492,                                                   // Requires Medallion Of Service
    AllPlayersMustHaveQuestTorghastTowerOfTheDamned = 493,                              // All Players Must Have Quest - Torghast: Tower Of The Damned.
    RequiresShadowlandsEngineering = 494,                                               // Requires Shadowlands Engineering
    YouAreNotInDeepEnoughWater = 495,                                                   // You Are Not In Deep Enough Water.
    RequiresFreshWatersOfArdenwealdOrBastion = 496,                                     // Requires The Fresh Waters Of Ardenweald Or Bastion
    Requires30InfusedRubies = 497,                                                      // Requires 30 Infused Rubies
    TheCurseOfTeramaniksLegacyIsKeepingYourMountsFromHeedingYourCall = 498,             // The Curse Of Teramanik'S Legacy Is Keeping Your Mounts From Heeding Your Call.
    YouDoNotKnowHowToTameCloudSerpents = 499,                                           // You Do Not Know How To Tame Cloud Serpents.
    YouDoNotKnowHowToTameUndeadCreatures = 500,                                         // You Do Not Know How To Tame Undead Creatures.
    RequiresTheForgeOfBonds = 501,                                                      // Requires The Forge Of Bonds
    RequiresGatamatos = 502,                                                            // Requires Gatamatos
    MustBeChannellingMindSear = 503,                                                    // Must Be Channelling Mind Sear.
    YouDontHaveAnyPeriodicEffectsActive = 504,                                          // You Don'T Have Any Periodic Effects Active.
    YouAreNotBestFriendsWithAnyEmberCourtGuests = 505,                                  // You Are Not Best Friends With Any Ember Court Guests.
    YouMustObtainVenomousSolvents = 506,                                                // You Must Obtain Venomous Solvents.
    YouMustObtainDreadPollen = 507,                                                     // You Must Obtain Dread Pollen.
    APartyMemberDoesNotHaveThatLayerUnlocked = 508,                                     // A Party Member Does Not Have That Layer Unlocked
    InventoryIsFull = 509,                                                              // Inventory Is Full.
    YouHaveNoAnimaToDeposit = 510,                                                      // You Have No Anima To Deposit
    YourMountIgnoresYourCallWithinTheMaw = 511,                                         // Your Mount Ignores Your Call Within The Maw.
    YourButlerIsAlreadyPresentSomewhereInTheEmberCourt = 512,                           // Your Butler Is Already Present Somewhere In The Ember Court.
    YouHaveAlreadyBuiltThisConstruct = 513,                                             // You Have Already Built This Construct
    RequiresInnerAltarOfDomination = 514,                                               // Requires Inner Altar Of Domination
    PartyMemberDoesNotMeetRequirementsToQueue = 515,                                    // A Party Member Does Not Meet The Requirements To Queue
    NoConstructCurrentlyActive = 516,                                                   // No Construct Currently Active
    CompleteTheQuestLineWelcomeToZandalar = 517,                                        // Complete The Quest Line "Welcome To Zandalar" To Use This Spell.
    CompleteTheQuestLineANationDivided = 518,                                           // Complete The Quest Line "A Nation Divided" To Use This Spell.
    CannotBeUsedOnCommonQualityItems = 519,                                             // Cannot Be Used On Common Quality Items.
    YouMustBePledgedToTheVenthyr = 520,                                                 // You Must Be Pledged To The Venthyr.
    YouMustBePledgedToTheNightFae = 521,                                                // You Must Be Pledged To The Night Fae.
    YouMustBePledgedToTheKyrian = 522,                                                  // You Must Be Pledged To The Kyrian.
    YouMustBePledgedToTheNecrolords = 523,                                              // You Must Be Pledged To The Necrolords.
    YouMustBeInTheShadowlands = 524,                                                    // You Must Be In The Shadowlands.
    RequiresSanctumReservoir = 525,                                                     // Requires Sanctum Reservoir.
    ThisWildseedOfRegrowthIsStillIncubating = 526,                                      // This Wildseed Of Regrowth Is Still Incubating.
    ThisWildseedOfRegrowthIsStillGrowing = 527,                                         // This Wildseed Of Regrowth Is Still Growing.
    YouMustBePartyLeaderToStartThisEscort = 528,                                        // You Must Be The Party Leader To Start This Escort.
    YouHaveFullyUpgradedAllOfYourConduits = 529,                                        // You Have Fully Upgraded All Of Your Conduits.
    YouHaveAlreadyAddedThatConduit = 530,                                               // You Have Already Added That Conduit To The Forge Of Bonds.
    TargetMustBeWeakened = 531,                                                         // Target Must Be Weakened.
    YouCannotAddThatConduitToForgeOfBonds = 532,                                        // You Cannot Add That Conduit To The Forge Of Bonds.
    YouCannotSoulshapeDuringLichborne = 533,                                            // You Cannot Soulshape During Lichborne.
    YouCantDoThatWhileCarryingAnAnimacone = 534,                                        // You Can'T Do That While Carrying An Animacone.
    NecessaryConstructNotPresent = 535,                                                 // Necessary Construct Not Present
    ThatGuestIsAlreadyCoveredInGelatin = 536,                                           // That Guest Is Already Covered In Gelatin.
    YouNeedToWaitToUseThisItem = 537,                                                   // You Need To Wait To Use This Item.
    ThatAllyAlreadyHasTea = 538,                                                        // That Ally Already Has Tea.
    TargetDoesNotNeedTea = 539,                                                         // The Target Does Not Need Tea.
    TheyDontDeserveYourFancyTea = 540,                                                  // They Don'T Deserve Your Fancy Tea!
    YourGormPrefersToEatDeadThings = 541,                                               // Your Gorm Prefers To Eat Dead Things.
    YourGormHasAlreadyEatenThatCorpse = 542,                                            // Your Gorm Has Already Eaten That Corpse.
    YouNeedAGormlingFromNiyaToDoThat = 543,                                             // You Need A Gormling From Niya To Do That.
    TargetIsAlreadyShrunken = 544,                                                      // Target Is Already Shrunken.
    TargetIsAlreadyEnlarged = 545,                                                      // Target Is Already Enlarged.
    LadyMoonberrysWandIsForEnemiesAndMawrats = 546,                                     // Lady Moonberry'S Wand Is Meant For Enemies And Mawrats.
    LadyMoonberrysWandIsForEnemies = 547,                                               // Lady Moonberry'S Wand Is Meant For Enemies.
    TargetIsAlreadyTransformedIntoASnail = 548,                                         // Target Is Already Transformed Into A Snail.
    YourTargetMustBeBelow50PctHealth = 549,                                             // Your Target Must Be Below 50% Health.
    LadyMoonberrysWandIsDrainedOfPower = 550,                                           // Lady Moonberry'S Wand Is Drained Of Power.
    ThisBookHoldsNoRecipesForYourProfession = 551,                                      // This Book Holds No Recipes For Your Profession.
    YouHaveNoKorthianRelicsInYourInventory = 552,                                       // You Have No Korthian Relics In Your Inventory.
    YouMustBeInTheRiftToInteractWithThis = 553,                                         // You Must Be In The Rift To Interact With This.
    CannotSummonWhileInTheRift = 554,                                                   // Cannot Summon While In The Rift.
    YouNeedAnActiveElementalShield = 600,                                               // You Need An Active Elemental Shield.
    SpeakToArchivistToTurnInRelicFragments = 601,                                       // Speak To The Archivist To Turn In Relic Fragments.
    RequiresResearchReportsAncientShrines = 602,                                        // Requires Knowledge From Research Reports: Ancient Shrines
    YourStewardIsNotPresent = 603,                                                      // Your Steward Companion Is Not Present.
    YourStewardHasAlreadyBeenTransformed = 604,                                         // Your Steward Companion Has Already Been Transformed.
    RequiresKorthianRelics = 605,                                                       // Requires Korthian Relics
    RequiresFullEmpoweredBar = 606,                                                     // Requires Full Empowered Bar
    RequiresYouToBeRidingAYak = 607,                                                    // Requires You To Be Riding A Yak.
    JaithysIsNotACannibal = 609,                                                        // Jaithys Is Many Things, But Jaithys Is Not A Cannibal.
    ThatItemIsPunyUnworthyFindAnother = 610,                                            // That Item Is Puny. Unworthy. Find Another.
    JaithysHungersOnlyForWeapons = 611,                                                 // Jaithys Hungers Only For Weapons. Only Weapons Will Do.
    ReturnToReliquaryOfRememberanceToSubmitKorthianRelics = 612,                        // Return To The Reliquary Of Rememberance To Submit Korthian Relics To Archivist Roh-Suir.
    ShardsOfDominationCanBeRemovedBySoulfireChisel = 615,                               // Shards Of Domination Can Only Be Removed By The Soulfire Chisel.
    YouHaveLearnedEverythingFromThatMap = 616,                                          // You Have Learned Everything From That Map.
    YouMustTargetACritterToHelpItAtoneForItsSins = 617,                                 // You Must Target A Critter To Help It Atone For Its Sins.
    YouMustBeAMemberOfTheKyrianCovenantOrHaveReachedRenown80WithTheKyrian = 619,        // You Must Be A Member Of The Kyrian Covenant Or Have Reached Renown 80 With The Kyrian.
    YouMustBeAMemberOfTheNecrolordCovenantOrHaveReachedRenown80WithTheNecrolords = 620, // You Must Be A Member Of The Necrolord Covenant Or Have Reached Renown 80 With The Necrolords.
    YouMustBeAMemberOfTheNightFaeCovenantOrHaveReachedRenown80WithTheNightFae = 621,    // You Must Be A Member Of The Night Fae Covenant Or Have Reached Renown 80 With The Night Fae.
    YouMustBeAMemberOfTheVenthyrCovenantOrHaveReachedRenown80WithTheVenthyr = 622,      // You Must Be A Member Of The Venthyr Covenant Or Have Reached Renown 80 With The Venthyr.
    YouAlreadyHaveThatMuchRenownWithYourActiveCovenant = 627,                           // You Already Have That Much Renown With Your Active Covenant.
    CannotExceedTheMaximumForThatCurrency = 628,                                        // Cannot Exceed The Maximum For That Currency.
    RequiresAdditionalCosmicEnergy = 629,                                               // Requires Additional Cosmic Energy.
    RequiresArchitect = 630,                                                            // Requires Architect.
    YouMustBeSittingToDoThat = 631,                                                     // You Must Be Sitting To Do That.
    RequiresPollenCloud = 632,                                                          // Requires Pollen Cloud.
    Requires5LostOvoids = 633,                                                          // Requires 5 Lost Ovoids.
    YouHaveTooManyTemporaryEnhancements = 634,                                          // You Have Too Many Temporary Enhancements.
    YouHaveOtherWaysToSummonPocopoc = 635,                                              // You Have Other Ways To Summon Pocopoc While In Zereth Mortis.
    RequiresMoreSyllabicRecall = 636,                                                   // Requires More Syllabic Recall.
    ThisBattlePetCannotRideOnMagicSaucer = 637,                                         // This Battle Pet Is Unable To Ride On The Magic Saucer.
    YouCanOnlyDoThisWhileMidair = 638,                                                  // You Can Only Do This While Midair.
    YouCannotDoThatWhileAirborne = 639,                                                 // You Cannot Do That While Airborne.
    PocopocIsUnavailableOnQuestline = 640,                                              // Pocopoc Is Unavailable To Summon During The Questline A Means To An End.
    RequiresSulfuronSlammer = 711,                                                      // Requires Sulfuron Slammer
    NotReadyYet = 788,                                                                  // Not Ready Yet.
    QualityOfTieredMedallionSettingIsTooLow = 789,                                      // The Quality Of Your Tiered Medallion Setting Is Too Low To Add Another Socket To This Item.
    YouHaveNotLearnedBarrelRoll = 790,                                                  // You Have Not Learned Barrel Roll.
    TargetMustBeAnEliteElemental = 791,                                                 // Target Must Be An Elite Elemental.
    SkillCheckAlreadyFailed = 792,                                                      // Skill Check Already Failed.
    YourTargetWasRecentlyFed = 793,                                                     // Your Target Was Recently Fed.
    CannotLureElusiveCreatureTowardsTown = 794,                                         // You Cannot Lure An Elusive Creature Towards A Town.
    NoWorthwhileCreaturesInAreaToLureOut = 795,                                         // There Are No Worthwhile Creatures In This Area To Lure Out.
    CannotLureWildBeast = 796,                                                          // This Is A Daycare For Whelps. Why Would You Try To Lure A Wild Beast Here...?
    YouHaveNoArcaneEssencesInYourInventory = 797,                                       // You Have No Arcane Essences In Your Inventory.
    ThatPlayerIsCurrentlyNotInterestedInEngagingWithYourShenanigans = 798,              // That Player Is Currently Not Interested In Engaging With Your Shenanigans.
    CantBeCastOnNonPlayerCharacters = 799,                                              // Can'T Be Cast On Non Player Characters.
    ASignalFlareWasRecentlyFiredAtThisLocation = 800,                                   // A Signal Flare Was Recently Fired At This Location.
    ThisTinkerIsTooComplicatedForYou = 801,                                             // This Tinker Is Too Complicated For You.
    TheDuckRefusesToPlayWhileAnotherMaestroIsNearby = 802,                              // The Duck Refuses To Play While Another Maestro Is Nearby.
    YouHaveStudiedTheseNotesExtensivelyandThereIsNothingNewToLearnFromThem = 803,       // You Have Studied These Notes Extensively And There Is Nothing New To Learn From Them.
    YouDontHaveEnoughGold = 804,                                                        // You Don'T Have Enough Gold.
    YouDoNotKnowHowToTameOttuk = 805,                                                   // You Do Not Know How To Tame Ottuk.
    ClanAylaagIsCurrentlyTravellingandCannotBeTeleportedTo = 806,                       // Clan Aylaag Is Currently Travelling And Cannot Be Teleported To.
    NotEnoughInsanity = 807,                                                            // Not Enough Insanity
    YouMustWaitToAccessThisAgain = 808,                                                 // You Must Wait To Access This Again.
    YouDoNotKnowHowToTameDragonkin = 809,                                               // You Do Not Know How To Tame Dragonkin.
    RequiresAnEmptySoulCage = 810,                                                      // Requires An Empty Soul Cage.
    YouAlreadyHaveACagedSoulOfThatType = 811,                                           // You Already Have A Caged Soul Of That Type.
    YouCantDoThatHere = 812,                                                            // You Can'T Do That Here.
    YouDoNotHaveAnyElementalGemsSocketed = 813,                                         // You Do Not Have Any Elemental Gems Socketed.
    YouMustBeInTheDragonIsles = 814,                                                    // You Must Be In The Dragon Isles.
    YouCannotDoThatWhileUnderwater = 815,                                               // You Cannot Do That While Underwater.
    YouMustBeRidingAStolenTameMagmammoth = 816,                                         // You Must Be Riding A Stolen Tame Magmammoth.
    YouMustBeFlyingAboveWaterInsideAnActiveTuskarrFishingHole = 817,                    // You Must Be Flying Above Water Inside An Active Tuskarr Fishing Hole.
    YouAreAlreadyBraveEnoughToContinueWithYourExperimentation = 818,                    // You Are Already Brave Enough To Continue With Your Experimentation.
    YouDontKnowHowToRepairThisItem = 819,                                               // You Don'T Know How To Repair This Item.
    ThereIsNoMoreRoomOnThatHandhold = 820,                                              // There Is No More Room On That Handhold.
    YouMustUnblockThisSpotByCompletingADailyQuest = 821,                                // You Must Unblock This Spot By Completing A Daily Quest.
    YouMustBeCloserToAnIceHoleToDoThat = 822,                                           // You Must Be Closer To An Ice Hole To Do That.
}