// Copyright (c) Forged WoW LLC <https://github.com/ForgedWoW/ForgedCore>
// Licensed under GPL-3.0 license. See <https://github.com/ForgedWoW/ForgedCore/blob/master/LICENSE> for full information.

namespace Framework.Constants;

public enum SmartActions
{
	None = 0,                            // No Action
	Talk = 1,                            // Groupid From CreatureText, Duration To Wait Before TextOver Event Is Triggered, useTalkTarget (0/1) - use target as talk target
	SetFaction = 2,                      // Factionid (Or 0 For Default)
	MorphToEntryOrModel = 3,             // CreatureTemplate Entry(Param1) Or Modelid (Param2) (Or 0 For Both To Demorph)
	Sound = 4,                           // Soundid, Textrange
	PlayEmote = 5,                       // Emoteid
	FailQuest = 6,                       // Questid
	OfferQuest = 7,                      // Questid, directAdd
	SetReactState = 8,                   // State
	ActivateGobject = 9,                 //
	RandomEmote = 10,                    // Emoteid1, Emoteid2, Emoteid3...
	Cast = 11,                           // Spellid, Castflags, TriggeredFlags
	SummonCreature = 12,                 // Creatureid, Summontype, Duration In Ms, Storageid, Attackinvoker, flags(SmartActionSummonCreatureFlags)
	ThreatSinglePct = 13,                // Threat%
	ThreatAllPct = 14,                   // Threat%
	CallAreaexploredoreventhappens = 15, // Questid
	SetIngamePhaseGroup = 16,            // phaseGroupId, apply
	SetEmoteState = 17,                  // Emoteid
	SetUnitFlag = 18,                    // UNUSED, DO NOT REUSE
	RemoveUnitFlag = 19,                 // UNUSED, DO NOT REUSE
	AutoAttack = 20,                     // Allowattackstate (0 = Stop Attack, Anything Else Means Continue Attacking)
	AllowCombatMovement = 21,            // Allowcombatmovement (0 = Stop Combat Based Movement, Anything Else Continue Attacking)
	SetEventPhase = 22,                  // Phase
	IncEventPhase = 23,                  // Value (May Be Negative To Decrement Phase, Should Not Be 0)
	Evade = 24,                          // No Params
	FleeForAssist = 25,                  // With Emote
	CallGroupeventhappens = 26,          // Questid
	CombatStop = 27,                     //
	RemoveAurasFromSpell = 28,           // Spellid, 0 Removes All Auras
	Follow = 29,                         // Distance (0 = Default), Angle (0 = Default), Endcreatureentry, Credit, Credittype (0monsterkill, 1event)
	RandomPhase = 30,                    // Phaseid1, Phaseid2, Phaseid3...
	RandomPhaseRange = 31,               // Phasemin, Phasemax
	ResetGobject = 32,                   //
	CallKilledmonster = 33,              // Creatureid,
	SetInstData = 34,                    // Field, Data, Type (0 = SetData, 1 = SetBossState)
	SetInstData64 = 35,                  // Field,
	UpdateTemplate = 36,                 // Entry
	Die = 37,                            // No Params
	SetInCombatWithZone = 38,            // No Params
	CallForHelp = 39,                    // Radius, With Emote
	SetSheath = 40,                      // Sheath (0-Unarmed, 1-Melee, 2-Ranged)
	ForceDespawn = 41,                   // Timer
	SetInvincibilityHpLevel = 42,        // Minhpvalue(+Pct, -Flat)
	MountToEntryOrModel = 43,            // CreatureTemplate Entry(Param1) Or Modelid (Param2) (Or 0 For Both To Dismount)
	SetIngamePhaseId = 44,               // Id
	SetData = 45,                        // Field, Data (Only Creature Todo)
	AttackStop = 46,
	SetVisibility = 47,                  // On/Off
	SetActive = 48,                      // No Params
	AttackStart = 49,                    //
	SummonGo = 50,                       // Gameobjectid, Despawntime In Ms,
	KillUnit = 51,                       //
	ActivateTaxi = 52,                   // Taxiid
	WpStart = 53,                        // Run/Walk, Pathid, Canrepeat, Quest, Despawntime
	WpPause = 54,                        // Time
	WpStop = 55,                         // Despawntime, Quest, Fail?
	AddItem = 56,                        // Itemid, Count
	RemoveItem = 57,                     // Itemid, Count
	InstallAITemplate = 58,              // UNUSED, DO NOT REUSE
	SetRun = 59,                         // 0/1
	SetDisableGravity = 60,              // 0/1
	SetSwim = 61,                        // UNUSED, DO NOT REUSE
	Teleport = 62,                       // Mapid,
	SetCounter = 63,                     // id, value, reset (0/1)
	StoreTargetList = 64,                // Varid,
	WpResume = 65,                       // None
	SetOrientation = 66,                 //
	CreateTimedEvent = 67,               // Id, Initialmin, Initialmax, Repeatmin(Only If It Repeats), Repeatmax(Only If It Repeats), Chance
	Playmovie = 68,                      // Entry
	MoveToPos = 69,                      // PointId, transport, disablePathfinding, ContactDistance
	EnableTempGobj = 70,                 //
	Equip = 71,                          // Entry, Slotmask Slot1, Slot2, Slot3   , Only Slots With Mask Set Will Be Sent To Client, Bits Are 1, 2, 4, Leaving Mask 0 Is Defaulted To Mask 7 (Send All), Slots1-3 Are Only Used If No Entry Is Set
	CloseGossip = 72,                    // None
	TriggerTimedEvent = 73,              // Id(>1)
	RemoveTimedEvent = 74,               // Id(>1)
	AddAura = 75,                        // UNUSED, DO NOT REUSE
	OverrideScriptBaseObject = 76,       // UNUSED, DO NOT REUSE
	ResetScriptBaseObject = 77,          // UNUSED, DO NOT REUSE
	CallScriptReset = 78,                // None
	SetRangedMovement = 79,              // Distance, Angle
	CallTimedActionlist = 80,            // Id (Overwrites Already Running Actionlist), Stop After Combat?(0/1), Timer Update Type(0-Ooc, 1-Ic, 2-Always)
	SetNpcFlag = 81,                     // Flags
	AddNpcFlag = 82,                     // Flags
	RemoveNpcFlag = 83,                  // Flags
	SimpleTalk = 84,                     // Groupid, Can Be Used To Make Players Say Groupid, TextOver Event Is Not Triggered, Whisper Can Not Be Used (Target Units Will Say The Text)
	SelfCast = 85,                       // Spellid, Castflags
	CrossCast = 86,                      // Spellid, Castflags, Castertargettype, Castertarget Param1, Castertarget Param2, Castertarget Param3, ( + The Origonal Target Fields As Destination Target),   Castertargets Will Cast Spellid On All Targets (Use With Caution If Targeting Multiple * Multiple Units)
	CallRandomTimedActionlist = 87,      // Script9 Ids 1-9
	CallRandomRangeTimedActionlist = 88, // Script9 Id Min, Max
	RandomMove = 89,                     // Maxdist
	SetUnitFieldBytes1 = 90,             // Bytes, Target
	RemoveUnitFieldBytes1 = 91,          // Bytes, Target
	InterruptSpell = 92,
	SendGoCustomAnim = 93,      // UNUSED, DO NOT REUSE
	SetDynamicFlag = 94,        // UNUSED, DO NOT REUSE
	AddDynamicFlag = 95,        // UNUSED, DO NOT REUSE
	RemoveDynamicFlag = 96,     // UNUSED, DO NOT REUSE
	JumpToPos = 97,             // SpeedXY, SpeedZ, Gravity, UseDefaultGravity, PointId, ContactDistance
	SendGossipMenu = 98,        // Menuid, optionIndex
	GoSetLootState = 99,        // State
	SendTargetToTarget = 100,   // Id
	SetHomePos = 101,           // None
	SetHealthRegen = 102,       // 0/1
	SetRoot = 103,              // Off/On
	SetGoFlag = 104,            // UNUSED, DO NOT REUSE
	AddGoFlag = 105,            // UNUSED, DO NOT REUSE
	RemoveGoFlag = 106,         // UNUSED, DO NOT REUSE
	SummonCreatureGroup = 107,  // Group, Attackinvoker
	SetPower = 108,             // PowerType, newPower
	AddPower = 109,             // PowerType, newPower
	RemovePower = 110,          // PowerType, newPower
	GameEventStop = 111,        // GameEventId
	GameEventStart = 112,       // GameEventId
	StartClosestWaypoint = 113, // wp1, wp2, wp3, wp4, wp5, wp6, wp7
	MoveOffset = 114,           // PointId
	RandomSound = 115,          // SoundId1, SoundId2, SoundId3, SoundId4, SoundId5, onlySelf
	SetCorpseDelay = 116,       // timer
	DisableEvade = 117,         // 0/1 (1 = disabled, 0 = enabled)
	GoSetGoState = 118,
	SetCanFly = 119,               // UNUSED, DO NOT REUSE
	RemoveAurasByType = 120,       // UNUSED, DO NOT REUSE
	SetSightDist = 121,            // UNUSED, DO NOT REUSE
	Flee = 122,                    // UNUSED, DO NOT REUSE
	AddThreat = 123,               // +threat, -threat
	LoadEquipment = 124,           // id
	TriggerRandomTimedEvent = 125, // id min range, id max range
	RemoveAllGameobjects = 126,    // UNUSED, DO NOT REUSE
	PauseMovement = 127,           // MovementSlot (default = 0, active = 1, controlled = 2), PauseTime (ms), Force
	PlayAnimkit = 128,
	ScenePlay = 129,                    // sceneId
	SceneCancel = 130,                  // sceneId
	SpawnSpawngroup = 131,              // Group ID, min secs, max secs, spawnflags
	DespawnSpawngroup = 132,            // Group ID, min secs, max secs, spawnflags
	RespawnBySpawnId = 133,             // spawnType, spawnId
	InvokerCast = 134,                  // spellID, castFlags
	PlayCinematic = 135,                // entry, cinematic
	SetMovementSpeed = 136,             // movementType, speedInteger, speedFraction
	PlaySpellVisualKit = 137,           // spellVisualKitId, kitType (unknown values, copypaste from packet dumps), duration
	OverrideLight = 138,                // zoneId, overrideLightID, transitionMilliseconds
	OverrideWeather = 139,              // zoneId, weatherId, intensity
	SetAIAnimKit = 140,                 // DEPRECATED, DO REUSE (it was never used in any branch, treat as free action id)
	SetHover = 141,                     // 0/1
	SetHealthPct = 142,                 // percent
	CreateConversation = 143,           // conversation_template.id
	SetImmunePC = 144,                  // 0/1
	SetImmuneNPC = 145,                 // 0/1
	SetUninteractible = 146,            // 0/1
	ActivateGameobject = 147,           // GameObjectActions
	AddToStoredTargetList = 148,        // varID
	BecomePersonalCloneForPlayer = 149, // summonType 1-8, duration in ms
	TriggerGameEvent = 150,             // eventId, useSaiTargetAsGameEventSource
	DoAction = 151,
	End
}